"""Structured content for the 10-situation ARP checkpoint."""


def option(key, text, feedback, misconception_code=None):
    return {"key": key, "text": text, "feedback": feedback, "misconception_code": misconception_code}


ACTIVITIES = [
    {
        "id": "1", "number": 1, "category": "Aplicar", "difficulty_level": 3,
        "type": "process_builder", "title": "Resolva o que falta", "primary": "ARP", "related": ["MAC", "FRAME"],
        "context_lines": ["PC-A · 192.168.10.25 · AA:AA:AA:AA:AA:AA", "PC-B · 192.168.10.80", "ARP Cache · sem entrada para .80"],
        "instruction": "Selecione e ordene somente os eventos necessários.",
        "events": ["DNS Request", "Consultar ARP Cache", "Usar MAC do gateway", "ARP Request", "ARP Reply", "Aprender MAC", "Preencher Destination MAC", "Enviar frame"],
        "correct_order": ["Consultar ARP Cache", "ARP Request", "ARP Reply", "Aprender MAC", "Preencher Destination MAC", "Enviar frame"],
        "feedback": {"DNS Request": "O IPv4 já é conhecido. DNS não fornece o MAC necessário.", "Usar MAC do gateway": "PC-B está localmente alcançável; o MAC necessário pertence ao próprio destino."},
        "misconceptions_by_event": {"DNS Request": "confuses_arp_with_dns", "Usar MAC do gateway": "confuses_remote_host_with_gateway"},
        "wrong_feedback": "Mantenha somente a consulta, a resolução ARP e o uso do MAC aprendido no frame.",
        "hint": "O cache é verificado antes de iniciar Request e Reply.",
        "correct_feedback": "Correto. O cache é consultado; ARP resolve e aprende o MAC; o endereço completa o frame antes da transmissão.",
    },
    {
        "id": "2", "number": 2, "category": "Aplicar", "difficulty_level": 3,
        "type": "packet_builder", "title": "Qual Request será enviado?", "primary": "ARP", "related": ["MAC"],
        "context_lines": ["PC-A: 192.168.10.25", "Destino local: 192.168.10.80"],
        "slots": [{"id": "target", "label": "WHO HAS"}, {"id": "sender", "label": "TELL"}, {"id": "ethernet", "label": "ETHERNET DESTINATION"}],
        "tokens": [{"id": "target-ip", "text": "192.168.10.80"}, {"id": "sender-ip", "text": "192.168.10.25"}, {"id": "broadcast", "text": "FF:FF:FF:FF:FF:FF"}, {"id": "gateway", "text": "192.168.10.1"}, {"id": "target-mac", "text": "BB:BB:BB:BB:BB:BB"}],
        "correct_map": {"target-ip": "target", "sender-ip": "sender", "broadcast": "ethernet"},
        "feedback": {"gateway": "O destino é local; o Request procura diretamente o IPv4 .80.", "target-mac": "O MAC ainda é desconhecido, por isso o Request usa broadcast Ethernet."},
        "misconceptions": {"gateway": "confuses_remote_host_with_gateway", "target-mac": "confuses_arp_with_mac"},
        "wrong_feedback": "O Request informa o IPv4 procurado, o IPv4 do solicitante e usa broadcast Ethernet.",
        "hint": "Who has recebe o alvo; Tell identifica quem está perguntando.",
        "correct_feedback": "Correto. Who has 192.168.10.80? Tell 192.168.10.25, enviado para FF:FF:FF:FF:FF:FF.",
    },
    {
        "id": "3", "number": 3, "category": "Aplicar", "difficulty_level": 3,
        "type": "event_selection", "title": "Cache já resolvido", "primary": "ARP", "related": ["FRAME"],
        "context_lines": ["ARP Cache: 192.168.10.80 → BB-BB-BB-BB-BB-BB", "PC-A precisa transmitir novamente para .80"],
        "instruction": "Selecione somente os eventos necessários e mantenha a ordem.",
        "events": ["Novo ARP Request obrigatório", "Consultar/utilizar entrada existente", "Novo ARP Reply obrigatório", "Preencher Destination MAC = BB-BB...", "Enviar frame"],
        "correct_order": ["Consultar/utilizar entrada existente", "Preencher Destination MAC = BB-BB...", "Enviar frame"],
        "feedback": {"Novo ARP Request obrigatório": "A associação útil já está disponível; uma nova descoberta imediata não é obrigatória.", "Novo ARP Reply obrigatório": "Sem um novo Request, não há motivo para exigir um novo Reply."},
        "misconceptions_by_event": {"Novo ARP Request obrigatório": "assumes_arp_required_for_every_frame", "Novo ARP Reply obrigatório": "assumes_arp_required_for_every_frame"},
        "wrong_feedback": "Use a associação já disponível antes de adicionar eventos de descoberta.",
        "hint": "A entrada válida permite preencher o frame diretamente.",
        "correct_feedback": "Correto. A associação existente fornece o Destination MAC e o frame pode ser enviado sem nova resolução imediata.",
    },
    {
        "id": "4", "number": 4, "category": "Inferir", "difficulty_level": 4,
        "type": "dual_builder", "title": "Destino remoto", "primary": "ARP", "related": ["MAC", "FRAME"],
        "context_lines": ["PC-A: 192.168.10.25", "Gateway: 192.168.10.1", "Destino final: 8.8.8.8", "ARP Cache: sem gateway"],
        "slots": [{"id": "arp", "label": "ARP DEVERÁ RESOLVER"}, {"id": "ip", "label": "IP DESTINATION DO PRIMEIRO FRAME"}, {"id": "mac", "label": "DESTINATION MAC DO PRIMEIRO FRAME"}],
        "tokens": [{"id": "gateway-ip", "text": "192.168.10.1"}, {"id": "remote-ip", "text": "8.8.8.8"}, {"id": "gateway-mac", "text": "MAC aprendido do gateway"}, {"id": "remote-mac", "text": "MAC de 8.8.8.8"}, {"id": "own-ip", "text": "192.168.10.25"}],
        "correct_map": {"gateway-ip": "arp", "remote-ip": "ip", "gateway-mac": "mac"},
        "feedback": {"remote-mac": "O host remoto não recebe diretamente o primeiro frame da LAN.", "own-ip": "Esse é o IPv4 da origem, não a informação a resolver."},
        "misconceptions": {"remote-mac": "confuses_remote_ip_with_destination_mac", "remote-ip": "confuses_remote_host_with_gateway"},
        "wrong_feedback": "Separe o destino IP final da próxima entrega Ethernet local.",
        "hint": "ARP resolve o próximo salto; o IP final continua remoto.",
        "correct_feedback": "Correto. ARP resolve 192.168.10.1; o IP continua 8.8.8.8; o primeiro frame usa o MAC do gateway.",
    },
    {
        "id": "5", "number": 5, "category": "Inferir", "difficulty_level": 4,
        "type": "terminal_analysis", "title": "Leia o terminal", "primary": "ARP", "related": ["MAC"],
        "context_lines": ["Destino final: 8.8.8.8", "Gateway: 192.168.10.1"],
        "capture": "C:\\> arp -a\n\n192.168.10.1    11-11-11-11-11-11\n192.168.10.80   BB-BB-BB-BB-BB-BB\n192.168.10.90   CC-CC-CC-CC-CC-CC",
        "question": "Qual associação evita uma nova descoberta ARP antes do primeiro frame?",
        "capture_fields": [
            option("gateway", "192.168.10.1 → 11-11-11-11-11-11", "Correto. O primeiro frame será entregue ao gateway."),
            option("local", "192.168.10.80 → BB-BB-BB-BB-BB-BB", "Essa entrada pertence a outro host local; o destino final apresentado é remoto.", "confuses_remote_host_with_gateway"),
            option("other", "192.168.10.90 → CC-CC-CC-CC-CC-CC", "Essa associação não corresponde ao próximo salto informado."),
        ],
        "correct": "gateway",
    },
    {
        "id": "6", "number": 6, "category": "Inferir", "difficulty_level": 4,
        "type": "compare_outputs", "title": "Antes × depois", "primary": "ARP", "related": ["FRAME"],
        "outputs": [{"title": "arp -a · antes", "text": "192.168.10.1 → 11-11-11-11-11-11"}, {"title": "ping 192.168.10.80 / arp -a · depois", "text": "192.168.10.1 → 11-11-11-11-11-11\n192.168.10.80 → BB-BB-BB-BB-BB-BB"}],
        "slots": [{"id": "change", "label": "MUDANÇA RELEVANTE"}, {"id": "field", "label": "CAMPO PREENCHIDO"}],
        "tokens": [{"id": "new", "text": "Nova associação .80 → BB-BB..."}, {"id": "destination", "text": "Destination MAC"}, {"id": "gateway", "text": "Gateway permaneceu igual"}, {"id": "source", "text": "Source MAC"}],
        "correct_map": {"new": "change", "destination": "field"},
        "feedback": {"gateway": "A linha já existia antes e não explica a nova possibilidade.", "source": "A associação aprendida representa o destino local, não a origem do frame."},
        "wrong_feedback": "Compare somente o que surgiu depois e relacione o MAC aprendido ao frame.",
        "hint": "Procure a nova linha e o campo que recebe o endereço do destinatário.",
        "correct_feedback": "Correto. A nova associação .80 → BB-BB... permite preencher diretamente o Destination MAC.",
    },
    {
        "id": "7", "number": 7, "category": "Inferir", "difficulty_level": 4,
        "type": "find_inconsistency", "title": "Captura inconsistente", "primary": "ARP", "related": ["MAC", "FRAME"],
        "context_lines": ["Destino local: 192.168.10.80", "ARP Cache: 192.168.10.80 → BB-BB-BB-BB-BB-BB", "11-11... pertence ao gateway"],
        "question": "Qual campo torna o frame incoerente com a resolução disponível?", "correct": "destination",
        "capture_fields": [option("source", "Source MAC · AA-AA-AA-AA-AA-AA", "A origem está coerente com PC-A."), option("destination", "Destination MAC · 11-11-11-11-11-11", "Correto. Para o destino local conhecido como BB-BB..., usar o MAC do gateway é incoerente.", "confuses_remote_host_with_gateway"), option("ip", "IPv4 Destination · 192.168.10.80", "O IPv4 coincide com o destino local informado.")],
    },
    {
        "id": "8", "number": 8, "category": "Inferir", "difficulty_level": 4,
        "type": "evidence_sort", "title": "Evidência × extrapolação", "primary": "ARP", "related": ["MAC", "FRAME"],
        "capture": "ARP Request → ARP Reply → ARP Cache atualizada → Frame usando o MAC aprendido",
        "slots": [{"id": "supported", "label": "SUSTENTADO", "capacity": "many"}, {"id": "unsupported", "label": "NÃO SUSTENTADO", "capacity": "many"}],
        "tokens": [{"id": "done", "text": "ARP foi concluído."}, {"id": "learned", "text": "O MAC necessário foi aprendido."}, {"id": "used", "text": "O frame utiliza o MAC aprendido."}, {"id": "app", "text": "A aplicação funciona necessariamente."}, {"id": "tcp", "text": "TCP está necessariamente estabelecido."}, {"id": "path", "text": "Todo o caminho está saudável."}],
        "correct_map": {"done": "supported", "learned": "supported", "used": "supported", "app": "unsupported", "tcp": "unsupported", "path": "unsupported"},
        "wrong_feedback": "ARP e o frame sustentam somente as etapas mostradas, não o restante da comunicação.",
        "hint": "Separe observação direta de conclusões que exigiriam outras evidências.",
        "correct_feedback": "Correto. As evidências confirmam resolução, aprendizado e uso do MAC, mas não garantem aplicação, TCP ou todo o caminho.",
    },
    {
        "id": "9", "number": 9, "category": "Diagnosticar", "difficulty_level": 5,
        "type": "diagnostic_map", "title": "Requests sem Reply", "primary": "ARP", "related": ["MAC"],
        "scenario": ["PC-A: 192.168.10.25", "Destino local: 192.168.10.80", "Who has .80? Tell .25 · repetido 3 vezes", "Nenhum Reply mostrado", "DNS: 8.8.8.8", "CPU: 5%"],
        "slots": [{"id": "observed", "label": "OBSERVADO", "capacity": "many"}, {"id": "cannot", "label": "NÃO POSSO AFIRMAR", "capacity": "many"}, {"id": "investigate", "label": "INVESTIGARIA PRIMEIRO", "capacity": "many"}],
        "tokens": [{"id": "trying", "text": "PC-A tenta resolver .80 e não há Reply mostrado."}, {"id": "offline", "text": "PC-B está definitivamente desligado."}, {"id": "local", "text": "Alcance local e contexto Ethernet da entrega."}, {"id": "dns", "text": "DNS é a causa."}, {"id": "cpu", "text": "CPU de 5% é a causa."}],
        "correct_map": {"trying": "observed", "offline": "cannot", "local": "investigate"},
        "feedback": {"dns": "O cenário usa diretamente um IPv4; nada sustenta DNS como causa.", "cpu": "O valor de CPU não demonstra relação causal."},
        "misconceptions": {"offline": "assumes_arp_reply_absence_proves_host_offline", "dns": "confuses_arp_with_dns"},
        "wrong_feedback": "Diferencie o que foi observado, o que não pode ser concluído e o próximo foco de investigação.",
        "hint": "Ausência de Reply descreve a etapa que falhou, mas não prova uma causa física específica.",
        "correct_feedback": "Correto. As evidências mostram resolução incompleta; a causa ainda não está provada e a investigação começa no contexto local.",
    },
    {
        "id": "10", "number": 10, "category": "Diagnosticar / Sintetizar", "difficulty_level": 5,
        "type": "integrated_concept_map", "title": "Sistema completo", "primary": "ARP", "related": ["MAC", "FRAME"],
        "slots": [{"id": "known", "label": "O HOST CONHECE"}, {"id": "missing", "label": "O QUE AINDA FALTA"}, {"id": "check", "label": "ONDE VERIFICA PRIMEIRO"}, {"id": "mechanism", "label": "MECANISMO SE NÃO ENCONTRAR"}, {"id": "learned", "label": "INFORMAÇÃO APRENDIDA"}, {"id": "used", "label": "ONDE É USADA"}],
        "tokens": [{"id": "ip", "text": "IPv4 relevante"}, {"id": "needed", "text": "MAC necessário"}, {"id": "cache", "text": "ARP Cache"}, {"id": "arp", "text": "ARP"}, {"id": "mac", "text": "Endereço MAC"}, {"id": "destination", "text": "Destination MAC do frame"}, {"id": "dns", "text": "DNS"}, {"id": "tcp", "text": "Porta TCP"}, {"id": "switch", "text": "Porta do switch"}],
        "correct_map": {"ip": "known", "needed": "missing", "cache": "check", "arp": "mechanism", "mac": "learned", "destination": "used"},
        "feedback": {"dns": "DNS não fornece o MAC quando o IPv4 já é conhecido.", "tcp": "A porta TCP não resolve endereçamento Ethernet.", "switch": "ARP não descobre portas do switch."},
        "misconceptions": {"dns": "confuses_arp_with_dns", "arp": "confuses_arp_with_mac", "switch": "confuses_arp_with_mac_table"},
        "wrong_feedback": "Reconstrua a sequência: informação conhecida, falta, cache, mecanismo, resultado e uso no frame.",
        "hint": "IPv4 → cache → ARP se necessário → MAC → Destination MAC.",
        "correct_feedback": "Correto. IPv4 conhecido → ARP Cache → ARP se necessário → MAC → Destination MAC do frame.",
        "free_question": "Explique com suas palavras por que ARP é necessário antes de alguns frames Ethernet, mas não antes de todos.",
        "reference": "ARP é necessário quando o host precisa de um endereço MAC para uma entrega IPv4 local e ainda não possui uma associação útil em sua ARP Cache. Quando essa associação já está conhecida e válida, o MAC pode ser utilizado diretamente no frame sem uma nova resolução imediata.",
        "reference_note": "Compare a relação entre cache disponível, necessidade de descoberta e uso do MAC no frame.",
    },
]


ACTIVITY_MAP = {activity["id"]: activity for activity in ACTIVITIES}
CAPABILITIES = ["Ordenar a resolução", "Construir Request", "Reutilizar cache", "Separar destino remoto", "Ler terminal", "Comparar saídas", "Detectar inconsistência", "Analisar evidências", "Diagnosticar", "Sintetizar"]
MISCONCEPTION_LABELS = {
    "confuses_arp_with_dns": "ARP × DNS", "confuses_arp_with_mac_table": "ARP Cache × tabela MAC",
    "confuses_arp_with_mac": "ARP × MAC", "confuses_remote_host_with_gateway": "Host remoto × gateway",
    "confuses_remote_ip_with_destination_mac": "IP remoto × Destination MAC",
    "assumes_arp_required_for_every_frame": "ARP obrigatório em todo frame",
    "assumes_arp_reply_absence_proves_host_offline": "Ausência de Reply × causa física",
}
