"""Structured content for the 10-activity Frame Ethernet checkpoint."""


def option(key, text, feedback, misconception_code=None):
    return {"key": key, "text": text, "feedback": feedback, "misconception_code": misconception_code}


ACTIVITIES = [
    {
        "id": "1", "number": 1, "category": "Aplicar", "difficulty_level": 3,
        "type": "frame_builder", "title": "Monte o frame local", "primary": "FRAME", "related": ["MAC"],
        "context_lines": ["PC-A · IPv4: 192.168.10.25 · MAC: AA:AA:AA:AA:AA:AA", "PC-B · IPv4: 192.168.10.80 · MAC: BB:BB:BB:BB:BB:BB"],
        "situation": "PC-A enviará dados diretamente para PC-B.",
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}, {"id": "data", "label": "DADOS"}],
        "tokens": [{"id": "mac-a", "text": "AA:AA:AA:AA:AA:AA"}, {"id": "mac-b", "text": "BB:BB:BB:BB:BB:BB"}, {"id": "ip-a", "text": "192.168.10.25"}, {"id": "ip-b", "text": "192.168.10.80"}, {"id": "report", "text": "\"Relatório\""}],
        "correct_map": {"mac-a": "source", "mac-b": "destination", "report": "data"},
        "feedback": {"ip-a": "O frame utiliza endereços MAC nesses dois campos.", "ip-b": "O frame utiliza endereços MAC nesses dois campos."},
        "misconceptions": {"ip-a": "confuses_mac_with_ip", "ip-b": "confuses_mac_with_ip", "mac-a": "confuses_source_and_destination_mac", "mac-b": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Reavalie quem está transmitindo e quem está recebendo a entrega Ethernet.",
        "hint": "Source acompanha quem transmite; Destination acompanha quem recebe aquele frame.",
        "correct_feedback": "Correto. O frame leva o MAC de PC-A como origem, o MAC de PC-B como destino e “Relatório” como dados.",
    },
    {
        "id": "2", "number": 2, "category": "Aplicar", "difficulty_level": 3,
        "type": "direction_builder", "title": "O frame de resposta", "primary": "FRAME", "related": ["MAC"],
        "context_lines": ["O frame anterior chegou a PC-B.", "Agora PC-B responderá a PC-A.", "MAC A: AA:AA:AA:AA:AA:AA", "MAC B: BB:BB:BB:BB:BB:BB"],
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "mac-a", "text": "AA:AA:AA:AA:AA:AA"}, {"id": "mac-b", "text": "BB:BB:BB:BB:BB:BB"}],
        "correct_map": {"mac-b": "source", "mac-a": "destination"},
        "misconceptions": {"mac-a": "confuses_source_and_destination_mac", "mac-b": "confuses_source_and_destination_mac"},
        "wrong_feedback": "A direção agora é PC-B → PC-A. Reavalie origem e destino deste frame de resposta.",
        "hint": "Source acompanha quem está respondendo.",
        "correct_feedback": "Correto. No frame de resposta, PC-B fornece o Source MAC e PC-A é o destino Ethernet.",
    },
    {
        "id": "3", "number": 3, "category": "Aplicar", "difficulty_level": 3,
        "type": "compare_outputs_builder", "title": "Complete com duas ferramentas", "primary": "FRAME", "related": ["MAC", "ARP"],
        "outputs": [{"title": "ipconfig /all", "text": "IPv4: 192.168.10.25\nPhysical Address: AA-BB-CC-DD-EE-FF\nGateway: 192.168.10.1"}, {"title": "arp -a", "text": "192.168.10.1    11-11-11-11-11-11\n192.168.10.80   BB-BB-BB-BB-BB-BB"}],
        "situation": "PC-A enviará um frame para 192.168.10.80.",
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "own", "text": "AA-BB-CC-DD-EE-FF"}, {"id": "gateway", "text": "11-11-11-11-11-11"}, {"id": "target", "text": "BB-BB-BB-BB-BB-BB"}],
        "correct_map": {"own": "source", "target": "destination"},
        "feedback": {"gateway": "O destino informado é o host local 192.168.10.80. A associação relevante é a desse próprio destino."},
        "misconceptions": {"gateway": "confuses_remote_ip_with_destination_mac", "own": "confuses_source_and_destination_mac", "target": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Cruze o Physical Address da própria interface com a associação ARP do destino informado.",
        "hint": "Uma saída mostra o MAC da origem; a outra mostra IPv4 → MAC conhecido pelo host.",
        "correct_feedback": "Correto. O Source MAC vem da interface de PC-A e o Destination MAC vem da associação ARP de 192.168.10.80.",
    },
    {
        "id": "4", "number": 4, "category": "Inferir", "difficulty_level": 4,
        "type": "dual_builder", "title": "Primeiro frame para fora da rede", "primary": "FRAME", "related": ["MAC", "ARP"],
        "context_lines": ["PC-A · IPv4: 192.168.10.25 · MAC: AA-AA-AA-AA-AA-AA", "Gateway · IPv4: 192.168.10.1 · MAC: 11-11-11-11-11-11", "Destino final: 8.8.8.8"],
        "slots": [{"id": "ip", "label": "IP DESTINATION"}, {"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC DO PRIMEIRO FRAME"}],
        "tokens": [{"id": "remote-ip", "text": "8.8.8.8"}, {"id": "gateway-ip", "text": "192.168.10.1"}, {"id": "source-mac", "text": "AA-AA-AA-AA-AA-AA"}, {"id": "gateway-mac", "text": "11-11-11-11-11-11"}, {"id": "remote-mac", "text": "MAC de 8.8.8.8"}],
        "correct_map": {"remote-ip": "ip", "source-mac": "source", "gateway-mac": "destination"},
        "feedback": {"gateway-ip": "O gateway recebe o primeiro frame, mas o destino IP da comunicação continua remoto.", "remote-mac": "O host remoto não recebe diretamente o primeiro frame da LAN."},
        "misconceptions": {"gateway-ip": "confuses_gateway_with_final_ip_destination", "remote-mac": "confuses_remote_ip_with_destination_mac", "source-mac": "confuses_source_and_destination_mac", "gateway-mac": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Separe o destino IP final da entrega Ethernet realizada no primeiro salto local.",
        "hint": "O IP continua remoto; o primeiro frame é entregue ao gateway.",
        "correct_feedback": "Correto. O IP continua apontando para 8.8.8.8, enquanto o primeiro frame usa o MAC de PC-A como origem e o MAC do gateway como destino.",
    },
    {
        "id": "5", "number": 5, "category": "Inferir", "difficulty_level": 4,
        "type": "capture_analysis", "title": "Essa captura faz sentido?", "primary": "FRAME", "related": ["MAC"],
        "context_lines": ["PC-A · 192.168.10.25 · AA-AA-AA-AA-AA-AA", "Gateway · 192.168.10.1 · 11-11-11-11-11-11", "Destino final: 8.8.8.8"],
        "capture": "Ethernet II\nSource: AA-AA-AA-AA-AA-AA\nDestination: 11-11-11-11-11-11\n\nIPv4\nSource: 192.168.10.25\nDestination: 8.8.8.8",
        "question": "A combinação de endereços mostrada é conceitualmente coerente com o primeiro frame?",
        "correct": "coherent", "options": [option("coherent", "COERENTE", "A combinação é coerente."), option("incoherent", "INCOERENTE", "O destino IP pode continuar remoto enquanto o primeiro frame é entregue Ethernet ao gateway.", "confuses_remote_ip_with_destination_mac")],
        "evidence_tokens": [{"id": "ip", "text": "Destination IP = 8.8.8.8"}, {"id": "mac", "text": "Destination MAC = gateway"}, {"id": "source", "text": "Source IP = 192.168.10.25"}, {"id": "gateway-ip", "text": "Gateway IP = 192.168.10.1"}],
        "correct_evidence": ["ip", "mac"],
        "wrong_feedback": "Selecione as duas evidências que explicam por que a combinação é coerente.",
        "hint": "Compare o destino final IP com quem recebe o primeiro frame localmente.",
        "correct_feedback": "Correto. O destino IP é remoto, enquanto a entrega Ethernet inicial é feita ao gateway.",
    },
    {
        "id": "6", "number": 6, "category": "Inferir", "difficulty_level": 4,
        "type": "event_selection_order", "title": "O que ainda precisa acontecer?", "primary": "FRAME", "related": ["ARP", "MAC"],
        "context_lines": ["PC-A: 192.168.10.25", "Destino local: 192.168.10.80", "ARP Cache: 192.168.10.1 → 11-11-11-11-11-11", "Sem entrada para 192.168.10.80", "PC-A possui dados prontos para enviar"],
        "instruction": "Selecione somente os eventos necessários e coloque-os na ordem correta.",
        "events": ["Consultar DNS", "Enviar ARP Request", "Consultar ARP Cache", "Usar MAC do gateway", "Receber ARP Reply", "Transmitir frame", "Aprender MAC de .80", "Preencher Destination MAC"],
        "correct_order": ["Consultar ARP Cache", "Enviar ARP Request", "Receber ARP Reply", "Aprender MAC de .80", "Preencher Destination MAC", "Transmitir frame"],
        "feedback": {"Consultar DNS": "O destino já foi fornecido como IPv4. DNS não obtém o MAC necessário ao frame.", "Usar MAC do gateway": "O destino está na rede local; o frame deve usar o MAC do próprio host .80."},
        "wrong_feedback": "Selecione apenas as etapas necessárias para descobrir o MAC do destino local, completar o frame e transmiti-lo.",
        "hint": "Antes de preencher Destination MAC, a associação de .80 precisa ser obtida e aprendida.",
        "correct_feedback": "Correto. A associação é consultada, descoberta por ARP, aprendida e então utilizada no frame antes da transmissão.",
    },
    {
        "id": "7", "number": 7, "category": "Inferir", "difficulty_level": 4,
        "type": "find_inconsistency", "title": "Encontre a inconsistência", "primary": "FRAME", "related": ["MAC", "ARP"],
        "context_lines": ["PC-A · IPv4: 192.168.10.25 · MAC: AA-AA-AA-AA-AA-AA", "Destino local: 192.168.10.80", "ARP Cache: 192.168.10.80 → BB-BB-BB-BB-BB-BB", "Gateway MAC conhecido: 11-11-11-11-11-11"],
        "capture_fields": [
            option("eth-source", "Ethernet Source · AA-AA-AA-AA-AA-AA", "Esse campo corresponde ao MAC da origem PC-A."),
            option("eth-destination", "Ethernet Destination · 11-11-11-11-11-11", "O destino IP está na mesma rede e PC-A já conhece seu MAC como BB-BB... O gateway não deveria ser o Destination MAC desse frame local.", "confuses_remote_ip_with_destination_mac"),
            option("ip-source", "IPv4 Source · 192.168.10.25", "Esse campo corresponde ao IPv4 de origem apresentado."),
            option("ip-destination", "IPv4 Destination · 192.168.10.80", "Esse campo corresponde ao destino IPv4 local apresentado."),
        ],
        "question": "Clique no campo que torna essa captura conceitualmente inconsistente com o cenário.", "correct": "eth-destination",
    },
    {
        "id": "8", "number": 8, "category": "Inferir", "difficulty_level": 4,
        "type": "evidence_sort", "title": "O que as evidências realmente provam?", "primary": "FRAME", "related": ["ARP", "MAC"],
        "capture": "ARP Reply: 192.168.10.80 is at BB-BB-BB-BB-BB-BB\n\nARP Cache: 192.168.10.80 → BB-BB-BB-BB-BB-BB\n\nEthernet Source: AA-AA-AA-AA-AA-AA\nEthernet Destination: BB-BB-BB-BB-BB-BB",
        "slots": [{"id": "supported", "label": "SUSTENTADO", "capacity": "many"}, {"id": "unsupported", "label": "NÃO SUSTENTADO", "capacity": "many"}],
        "tokens": [{"id": "known", "text": "PC-A conhece um MAC associado a 192.168.10.80."}, {"id": "addressed", "text": "O frame observado está endereçado Ethernet para BB-BB..."}, {"id": "arp-done", "text": "A resolução ARP apresentada foi concluída."}, {"id": "app", "text": "O aplicativo no destino está necessariamente funcionando."}, {"id": "tcp", "text": "Existe necessariamente uma sessão TCP estabelecida."}, {"id": "all", "text": "Todo o caminho de comunicação está funcionando corretamente."}],
        "correct_map": {"known": "supported", "addressed": "supported", "arp-done": "supported", "app": "unsupported", "tcp": "unsupported", "all": "unsupported"},
        "wrong_feedback": "Evidências de ARP e Ethernet confirmam etapas específicas, não todo o restante da comunicação.",
        "hint": "Separe o que aparece diretamente nos dados daquilo que exigiria evidências adicionais.",
        "correct_feedback": "Correto. Evidências de ARP e Ethernet confirmam etapas específicas, não todo o restante da comunicação.",
    },
    {
        "id": "9", "number": 9, "category": "Diagnosticar", "difficulty_level": 5,
        "type": "diagnostic_map", "title": "O ping falha, mas o frame está certo", "primary": "FRAME", "related": ["ARP", "MAC"],
        "scenario": ["PC-A: 192.168.10.25", "Destino local: 192.168.10.80", "ARP Cache: 192.168.10.80 → BB-BB-BB-BB-BB-BB", "Source MAC: AA-AA-AA-AA-AA-AA", "Destination MAC: BB-BB-BB-BB-BB-BB", "ping 192.168.10.80 falha", "DNS: 8.8.8.8", "CPU: 6%"],
        "slots": [{"id": "affirm", "label": "JÁ POSSO AFIRMAR", "capacity": "many"}, {"id": "less", "label": "FICA MENOS PROVÁVEL", "capacity": "many"}, {"id": "unknown", "label": "AINDA NÃO POSSO AFIRMAR", "capacity": "many"}],
        "tokens": [{"id": "association", "text": "PC-A possui associação MAC para o destino."}, {"id": "frame", "text": "O frame apresentado utiliza esse MAC como destino Ethernet."}, {"id": "arp-less", "text": "Uma falha na descoberta ARP do MAC de 192.168.10.80."}, {"id": "all-ok", "text": "Toda a comunicação funciona corretamente."}, {"id": "off", "text": "O host remoto está necessariamente desligado."}, {"id": "dns", "text": "DNS é a causa."}, {"id": "cpu", "text": "CPU de 6% está causando a falha."}],
        "correct_map": {"association": "affirm", "frame": "affirm", "arp-less": "less", "all-ok": "unknown", "off": "unknown"},
        "feedback": {"dns": "O teste utiliza diretamente um IPv4 e nada apresentado aponta especificamente para DNS.", "cpu": "O valor de CPU apresentado não demonstra relação causal com a falha."},
        "wrong_feedback": "Use as evidências para reduzir hipóteses sem afirmar uma causa que ainda não foi demonstrada.",
        "hint": "ARP e o endereçamento Ethernet parecem concluídos; isso não prova todas as etapas seguintes.",
        "correct_feedback": "Correto. Diagnóstico também consiste em eliminar hipóteses que já não combinam bem com as evidências observadas.",
    },
    {
        "id": "10", "number": 10, "category": "Diagnosticar / Sintetizar", "difficulty_level": 5,
        "type": "integrated_concept_map", "title": "Do dado ao frame", "primary": "FRAME", "related": ["MAC", "ARP"],
        "context_lines": ["PC-A possui dados para 192.168.10.80", "ARP Cache inicialmente sem entrada para esse host"],
        "slots": [{"id": "initial", "label": "1. O QUE EXISTE INICIALMENTE?"}, {"id": "missing", "label": "2. QUAL INFORMAÇÃO ETHERNET AINDA FALTA?"}, {"id": "mechanism", "label": "3. QUAL MECANISMO PODE OBTÊ-LA?"}, {"id": "learned", "label": "4. QUAL INFORMAÇÃO É APRENDIDA?"}, {"id": "used", "label": "5. ONDE ELA SERÁ UTILIZADA?"}, {"id": "transmitted", "label": "6. O QUE FINALMENTE PODE SER TRANSMITIDO?"}],
        "tokens": [{"id": "data", "text": "Dados"}, {"id": "needed", "text": "Destination MAC"}, {"id": "arp", "text": "ARP"}, {"id": "mac", "text": "Endereço MAC"}, {"id": "frame-dest", "text": "Destination MAC do frame"}, {"id": "frame", "text": "Frame Ethernet"}, {"id": "dns", "text": "DNS"}, {"id": "tcp", "text": "Porta TCP"}, {"id": "switch", "text": "Porta do switch"}],
        "correct_map": {"data": "initial", "needed": "missing", "arp": "mechanism", "mac": "learned", "frame-dest": "used", "frame": "transmitted"},
        "feedback": {"dns": "O IPv4 já é conhecido; DNS não fornece o Destination MAC do frame.", "tcp": "A porta TCP não preenche o endereço Ethernet necessário.", "switch": "ARP não descobre uma porta do switch."},
        "misconceptions": {"dns": "confuses_arp_with_mac", "tcp": "confuses_frame_with_ip_packet", "switch": "confuses_frame_with_mac", "arp": "confuses_arp_with_mac"},
        "wrong_feedback": "Reconstrua a sequência separando dados, informação que falta, mecanismo, informação aprendida e estrutura transmitida.",
        "hint": "ARP obtém o MAC; o MAC entra no campo de destino; o frame completo é transmitido.",
        "correct_feedback": "Correto. DADOS → DESTINATION MAC NECESSÁRIO → ARP → MAC APRENDIDO → FRAME COMPLETADO → TRANSMISSÃO.",
        "free_question": "Explique com suas palavras como ARP, MAC e Frame Ethernet participam de uma mesma comunicação.",
        "reference": "O frame Ethernet é a estrutura utilizada para transportar dados na comunicação Ethernet. Ele utiliza endereços MAC de origem e destino. Se o host conhece o IPv4 relevante, mas ainda não conhece o MAC necessário para a entrega local, ARP pode descobrir essa associação. Depois que o MAC é aprendido, ele pode ser usado como Destination MAC do frame, permitindo que a transmissão Ethernet prossiga.",
        "reference_note": "Você não precisa usar as mesmas palavras. O importante é distinguir claramente o papel de cada conceito e explicar como eles se conectam.",
    },
]


ACTIVITY_MAP = {activity["id"]: activity for activity in ACTIVITIES}
CAPABILITIES = ["Construir frames", "Interpretar Source/Destination", "Cruzar terminal + ARP", "Separar IP e MAC", "Interpretar captura", "Ordenar processo", "Detectar inconsistência", "Analisar evidências", "Diagnosticar", "Explicar"]
MISCONCEPTION_LABELS = {
    "confuses_frame_with_mac": "Frame × MAC",
    "confuses_frame_with_ip_packet": "Frame × pacote IP",
    "confuses_source_and_destination_mac": "Source MAC × Destination MAC",
    "confuses_mac_with_ip": "MAC × IPv4",
    "confuses_arp_with_mac": "ARP × MAC",
    "confuses_remote_ip_with_destination_mac": "Destino remoto × Destination MAC",
    "confuses_gateway_with_final_ip_destination": "Gateway × destino IP final",
}
