"""Structured checkpoint for ICMP, Ping and Traceroute."""


def field(name, label, options=None):
    return {"name": name, "label": label, "options": options or []}


HINTS = [
    "Separe primeiro o que foi diretamente observado da hipótese sobre a causa.",
    "Use somente as respostas recebidas, os TTLs e os hops posteriores como evidência.",
]


ACTIVITIES = [
    {
        "id": "1", "number": 1, "category": "Classificar", "difficulty_level": 3,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["IPv4"],
        "title": "Request × Reply", "scenario": "A → B: ICMP Echo Request · B → A: ICMP Echo Reply",
        "instruction": "Associe cada mensagem ao seu papel.",
        "fields": [field("a_to_b", "A → B", ["INICIA O TESTE", "RESPONDE AO TESTE"]), field("b_to_a", "B → A", ["INICIA O TESTE", "RESPONDE AO TESTE"])],
        "correct_map": {"a_to_b": "inicia o teste", "b_to_a": "responde ao teste"},
        "feedback": {"a_to_b": "Echo Request inicia a troca estudada.", "b_to_a": "Echo Reply é a resposta correspondente."},
        "misconceptions": {"a_to_b": "confuses_echo_request_with_echo_reply", "b_to_a": "confuses_echo_request_with_echo_reply"},
        "wrong_feedback": "Observe a direção e o tipo ICMP de cada mensagem.",
        "correct_feedback": "Correto. A envia Echo Request e B retorna Echo Reply.", "hints": [],
    },
    {
        "id": "2", "number": 2, "category": "Interpretar", "difficulty_level": 3,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["IPv4"],
        "title": "Calcular a perda", "scenario": "Sent = 4 · Received = 3 · Lost = 1",
        "instruction": "Informe a perda e diga se ela identifica a causa.",
        "fields": [field("loss", "Loss"), field("cause", "Identifica a causa?", ["SIM", "NÃO"])],
        "correct_map": {"loss": "25%", "cause": "não"},
        "feedback": {"loss": "Uma de quatro trocas não foi concluída.", "cause": "Perda é uma medição, não uma causa."},
        "misconceptions": {"cause": "assumes_packet_loss_identifies_the_cause"},
        "wrong_feedback": "Calcule a fração perdida e não transforme a medição em diagnóstico.",
        "correct_feedback": "Correto. A perda foi 25%, mas o resultado não identifica sua causa.", "hints": [],
    },
    {
        "id": "3", "number": 3, "category": "Diferenciar", "difficulty_level": 4,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["IPv4"],
        "title": "Ping funciona, site não abre", "scenario": "Ping ao servidor recebe Echo Reply. O usuário não consegue abrir o sistema web.",
        "instruction": "Escolha a conclusão mais segura.",
        "fields": [field("conclusion", "Conclusão", ["A TROCA ICMP FUNCIONOU; O SERVIÇO AINDA NÃO FOI TESTADO", "TODA A REDE E O SERVIÇO ESTÃO FUNCIONANDO"])],
        "correct_map": {"conclusion": "a troca icmp funcionou; o serviço ainda não foi testado"},
        "feedback": {"conclusion": "Echo Reply comprova somente a troca ICMP observada."},
        "misconceptions": {"conclusion": "assumes_ping_success_means_everything_is_working"},
        "wrong_feedback": "Ping e o serviço da aplicação são testes diferentes.",
        "correct_feedback": "Correto. Há evidência positiva de ICMP; o serviço precisa ser testado separadamente.", "hints": [],
    },
    {
        "id": "4", "number": 4, "category": "Diferenciar", "difficulty_level": 4,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["IPv4"],
        "title": "Interpretar timeout", "scenario": "Request timed out.",
        "instruction": "Separe observado de não comprovado.",
        "fields": [field("observed", "Observado", ["ECHO REPLY NÃO VOLTOU NO PRAZO", "SERVIDOR ESTÁ DESLIGADO"]), field("not_proven", "Não comprovado", ["SERVIDOR ESTÁ DESLIGADO", "NÃO HOUVE ECHO REPLY NO PRAZO"])],
        "correct_map": {"observed": "echo reply não voltou no prazo", "not_proven": "servidor está desligado"},
        "feedback": {"observed": "Timeout descreve a ausência da resposta esperada.", "not_proven": "A causa não é determinada por esse resultado."},
        "misconceptions": {"observed": "assumes_ping_timeout_means_host_is_off", "not_proven": "jumps_from_evidence_to_root_cause"},
        "wrong_feedback": "Vários pontos podem impedir ou ocultar uma resposta ICMP. Separe observação de hipótese.",
        "correct_feedback": "Correto. Não houve Echo Reply no prazo; servidor desligado é apenas uma hipótese.", "hints": [],
    },
    {
        "id": "5", "number": 5, "category": "Interpretar", "difficulty_level": 4,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["Gateway", "Routing"],
        "title": "Quem enviou Unreachable?", "scenario": "Reply from 192.168.10.1: Destination host unreachable.",
        "instruction": "Identifique quem gerou a mensagem observada.",
        "fields": [field("sender", "Emissor")], "correct_map": {"sender": "192.168.10.1"},
        "feedback": {"sender": "O próprio texto identifica o endereço que enviou a mensagem explícita."},
        "misconceptions": {"sender": "jumps_from_evidence_to_root_cause"},
        "wrong_feedback": "Leia o endereço após “Reply from”; não tente diagnosticar a causa.",
        "correct_feedback": "Correto. A mensagem observada foi enviada por 192.168.10.1.", "hints": [],
    },
    {
        "id": "6", "number": 6, "category": "Aplicar", "difficulty_level": 4,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["IPv4", "Routing"],
        "title": "Sonda com TTL 2", "scenario": "A → R1 → R2 → R3 → B · TTL inicial = 2",
        "instruction": "Em qual roteador o TTL expira neste modelo?",
        "fields": [field("hop", "Expira em", ["R1", "R2", "R3", "B"])], "correct_map": {"hop": "r2"},
        "feedback": {"hop": "R1 reduz 2→1; R2 reduz 1→0 e descarta a sonda."},
        "misconceptions": {"hop": "ignores_ttl_decrement"},
        "wrong_feedback": "Acompanhe uma redução do TTL a cada roteador atravessado.",
        "correct_feedback": "Correto. Com TTL 2, a sonda expira em R2.", "hints": [], "stage_ttl": 2,
    },
    {
        "id": "7", "number": 7, "category": "Sintetizar", "difficulty_level": 5,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["IPv4", "Routing"],
        "title": "Construir o Traceroute", "scenario": "A → R1 → R2 → R3 → B",
        "instruction": "Associe cada TTL ao ponto revelado.",
        "fields": [field("ttl1", "TTL 1", ["R1", "R2", "R3", "B"]), field("ttl2", "TTL 2", ["R1", "R2", "R3", "B"]), field("ttl3", "TTL 3", ["R1", "R2", "R3", "B"]), field("ttl4", "TTL 4", ["R1", "R2", "R3", "B"])],
        "correct_map": {"ttl1": "r1", "ttl2": "r2", "ttl3": "r3", "ttl4": "b"},
        "feedback": {"ttl1": "O primeiro roteador esgota TTL 1.", "ttl2": "TTL 2 alcança R2.", "ttl3": "TTL 3 alcança R3.", "ttl4": "TTL 4 alcança o destino neste cenário."},
        "misconceptions": {"ttl1": "assumes_traceroute_knows_path_in_advance", "ttl2": "ignores_ttl_decrement"},
        "wrong_feedback": "Aumente o limite em um salto por vez.",
        "correct_feedback": "Correto. TTLs crescentes revelam R1, R2, R3 e então B.", "hints": HINTS, "stage_ttl": 1,
    },
    {
        "id": "8", "number": 8, "category": "Diagnosticar", "difficulty_level": 5,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["Routing"],
        "title": "Hop com asterisco", "scenario": "1 R1 · 2 * · 3 R3 · 4 B",
        "instruction": "Avalie a afirmação: “R2 parou e não encaminha tráfego”.",
        "fields": [field("verdict", "Conclusão", ["NÃO É SUSTENTADA", "É COMPROVADA"])],
        "correct_map": {"verdict": "não é sustentada"},
        "feedback": {"verdict": "R3 e B responderam; as sondas avançaram além do hop 2."},
        "misconceptions": {"verdict": "assumes_missing_traceroute_hop_means_forwarding_stopped"},
        "wrong_feedback": "Observe os hops posteriores: eles só podem responder se a sonda avançou além do segundo salto.",
        "correct_feedback": "Correto. Ausência de resposta do hop 2 não prova ausência de forwarding.", "hints": HINTS,
        "evidence": ["Hop 2 não respondeu", "R3 respondeu no hop 3", "B respondeu no hop 4"],
    },
    {
        "id": "9", "number": 9, "category": "Diagnosticar", "difficulty_level": 5,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["Subnet", "Gateway", "Routing"],
        "title": "Restringir a investigação", "scenario": "Ping 192.168.10.80 → Reply · Ping 192.168.10.1 → Reply · Ping 192.168.50.30 → Timeout · Tracert: 1 R1, 2 R2, 3 *",
        "instruction": "Escolha a conclusão sustentada.",
        "fields": [field("conclusion", "Conclusão", ["INTERFACE LOCAL E ACESSO AO GATEWAY FUNCIONARAM NOS TESTES", "O ROTEADOR SEGUINTE É NECESSARIAMENTE A CAUSA"])],
        "correct_map": {"conclusion": "interface local e acesso ao gateway funcionaram nos testes"},
        "feedback": {"conclusion": "Os replies local e do gateway reduzem hipóteses; não determinam a causa remota."},
        "misconceptions": {"conclusion": "jumps_from_evidence_to_root_cause"},
        "wrong_feedback": "Use os resultados para restringir a investigação, não para nomear um culpado.",
        "correct_feedback": "Correto. Há evidência positiva local e até o gateway, mas a causa remota permanece aberta.", "hints": HINTS,
        "evidence": ["Host local respondeu", "Gateway local respondeu", "Destino remoto não retornou Echo Reply", "Traceroute observou R1 e R2"],
    },
    {
        "id": "10", "number": 10, "category": "Diagnosticar / Sintetizar", "difficulty_level": 5,
        "primary": "ICMP / PING / TRACEROUTE", "related": ["IPv4", "Gateway", "Routing", "Frame"],
        "title": "Diagnostic Path Challenge", "scenario": "PC-A → R1 → R2 → R3 → SERVER · Usuário: “o servidor está fora” · Ping: timeout · Tracert: 1 R1, 2 R2, 3 R3, 4 *",
        "instruction": "Registre a evidência e a conclusão segura.",
        "fields": [field("observed", "Observado", ["SEM ECHO REPLY", "SERVIDOR DESLIGADO"]), field("reach", "Traceroute observou até", ["R1", "R2", "R3", "SERVER"]), field("exact_cause", "Causa exata determinada?", ["SIM", "NÃO"]), field("conclusion", "Conclusão", ["TRÁFEGO AVANÇOU ATÉ R3; CAUSA FINAL NÃO DETERMINADA", "R3 É A CAUSA"])],
        "correct_map": {"observed": "sem echo reply", "reach": "r3", "exact_cause": "não", "conclusion": "tráfego avançou até r3; causa final não determinada"},
        "feedback": {"observed": "Timeout descreve ausência de Reply.", "reach": "R3 respondeu à sonda.", "exact_cause": "Os dois testes não isolam a causa final.", "conclusion": "A conclusão deve permanecer dentro das evidências."},
        "misconceptions": {"observed": "assumes_ping_timeout_means_host_is_off", "exact_cause": "jumps_from_evidence_to_root_cause", "conclusion": "jumps_from_evidence_to_root_cause"},
        "wrong_feedback": "Não procure um culpado: separe resposta observada, alcance demonstrado e causa ainda desconhecida.",
        "correct_feedback": "Correto. Houve avanço observado até R3, mas Ping e Traceroute não determinam a causa final.", "hints": HINTS,
        "evidence": ["Ping não recebeu Echo Reply", "R1 respondeu", "R2 respondeu", "R3 respondeu", "Destino não forneceu a resposta esperada"],
    },
]

ACTIVITY_MAP = {item["id"]: item for item in ACTIVITIES}
CAPABILITIES = ["Distinguir Echo Request e Reply", "Interpretar RTT, perda, timeout e unreachable", "Explicar TTL e Time Exceeded", "Interpretar hops ausentes", "Separar evidência de hipótese"]
MISCONCEPTION_LABELS = {
    "assumes_ping_tests_all_network_services":"Supõe que Ping testa todos os serviços", "assumes_ping_success_means_everything_is_working":"Interpreta Ping OK como tudo funcionando",
    "assumes_ping_timeout_means_host_is_off":"Interpreta timeout como host desligado", "assumes_packet_loss_identifies_the_cause":"Trata perda como causa",
    "confuses_echo_request_with_echo_reply":"Confunde Echo Request e Echo Reply", "confuses_icmp_with_tcp":"Confunde ICMP com TCP",
    "assumes_ping_uses_a_tcp_port":"Supõe que Ping usa porta TCP", "assumes_rtt_is_one_way_latency":"Interpreta RTT como tempo de ida",
    "assumes_traceroute_knows_path_in_advance":"Supõe que Traceroute conhece o caminho", "assumes_traceroute_queries_router_list":"Supõe que Traceroute consulta uma lista de roteadores",
    "ignores_ttl_decrement":"Ignora o decremento do TTL", "assumes_ttl_is_seconds_in_modern_forwarding":"Interpreta TTL como segundos",
    "assumes_missing_traceroute_hop_means_forwarding_stopped":"Interpreta * como forwarding interrompido", "assumes_every_hop_must_reply":"Supõe que todo hop precisa responder",
    "assumes_forward_and_return_paths_are_identical":"Supõe caminhos de ida e volta idênticos", "assumes_traceroute_path_is_permanent":"Trata o caminho como permanente",
    "confuses_time_exceeded_with_echo_reply":"Confunde Time Exceeded e Echo Reply", "jumps_from_evidence_to_root_cause":"Salta da evidência para a causa raiz",
}
