"""Conteúdo estruturado do checkpoint ativo de MAC Address."""


def option(key, text, feedback, misconception_code=None):
    return {"key": key, "text": text, "feedback": feedback, "misconception_code": misconception_code}


ACTIVITIES = [
    {
        "id": "1", "number": 1, "category": "Aplicar", "difficulty_level": 3,
        "type": "frame_builder", "title": "Monte a entrega local", "primary": "MAC", "related": ["FRAME"],
        "context_lines": ["PC-A · MAC AA-AA-AA-AA-AA-AA", "PC-B · MAC BB-BB-BB-BB-BB-BB", "PC-A transmite para PC-B"],
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "mac-a", "text": "AA-AA-AA-AA-AA-AA"}, {"id": "mac-b", "text": "BB-BB-BB-BB-BB-BB"}, {"id": "ip-a", "text": "192.168.10.25"}, {"id": "ip-b", "text": "192.168.10.80"}],
        "correct_map": {"mac-a": "source", "mac-b": "destination"},
        "feedback": {"ip-a": "Esse valor é um IPv4, não o endereço Ethernet solicitado.", "ip-b": "Esse valor é um IPv4, não o endereço Ethernet solicitado."},
        "misconceptions": {"ip-a": "confuses_mac_with_ip", "ip-b": "confuses_mac_with_ip", "mac-a": "confuses_source_and_destination_mac", "mac-b": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Source acompanha PC-A, que origina o frame; Destination acompanha PC-B, que recebe a entrega Ethernet.",
        "hint": "Observe a direção PC-A → PC-B.",
        "correct_feedback": "Correto. Source MAC recebe AA-AA... e Destination MAC recebe BB-BB....",
    },
    {
        "id": "2", "number": 2, "category": "Aplicar", "difficulty_level": 3,
        "type": "direction_builder", "title": "Monte o frame de resposta", "primary": "MAC", "related": ["FRAME"],
        "context_lines": ["O frame anterior chegou.", "Agora PC-B responde a PC-A.", "PC-A · AA-AA-AA-AA-AA-AA", "PC-B · BB-BB-BB-BB-BB-BB"],
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "mac-a", "text": "AA-AA-AA-AA-AA-AA"}, {"id": "mac-b", "text": "BB-BB-BB-BB-BB-BB"}],
        "correct_map": {"mac-b": "source", "mac-a": "destination"},
        "misconceptions": {"mac-a": "confuses_source_and_destination_mac", "mac-b": "confuses_source_and_destination_mac"},
        "wrong_feedback": "A direção agora é PC-B → PC-A.",
        "hint": "Source acompanha quem responde.",
        "correct_feedback": "Correto. Na resposta, BB-BB... é Source e AA-AA... é Destination.",
    },
    {
        "id": "3", "number": 3, "category": "Aplicar", "difficulty_level": 3,
        "type": "compare_outputs", "title": "Cruze duas ferramentas", "primary": "MAC", "related": ["ARP", "FRAME"],
        "outputs": [{"title": "ipconfig /all", "text": "Physical Address: AA-AA-AA-AA-AA-AA\nIPv4: 192.168.10.25"}, {"title": "arp -a", "text": "192.168.10.80    BB-BB-BB-BB-BB-BB"}],
        "situation": "PC-A envia para 192.168.10.80.",
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "own", "text": "AA-AA-AA-AA-AA-AA"}, {"id": "target", "text": "BB-BB-BB-BB-BB-BB"}, {"id": "own-ip", "text": "192.168.10.25"}, {"id": "target-ip", "text": "192.168.10.80"}],
        "correct_map": {"own": "source", "target": "destination"},
        "feedback": {"own-ip": "ipconfig também mostra IPv4, mas o campo solicitado é MAC.", "target-ip": "arp -a relaciona esse IPv4 ao MAC BB-BB...."},
        "misconceptions": {"own-ip": "confuses_mac_with_ip", "target-ip": "confuses_mac_with_ip", "own": "confuses_source_and_destination_mac", "target": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Use o Physical Address como origem e a associação de .80 como destino.",
        "hint": "Uma saída mostra o MAC da própria interface; a outra mostra o MAC conhecido para .80.",
        "correct_feedback": "Correto. ipconfig /all fornece o Source MAC e arp -a fornece o Destination MAC local.",
    },
    {
        "id": "4", "number": 4, "category": "Inferir", "difficulty_level": 4,
        "type": "topology_builder", "title": "Destino remoto", "primary": "MAC", "related": ["FRAME"],
        "context_lines": ["PC-A · IP 192.168.10.25 · MAC AA-AA-AA-AA-AA-AA", "Gateway · IP 192.168.10.1 · MAC 11-11-11-11-11-11", "Destino final · 8.8.8.8"],
        "slots": [{"id": "ip", "label": "IP DESTINATION"}, {"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "remote-ip", "text": "8.8.8.8"}, {"id": "gateway-ip", "text": "192.168.10.1"}, {"id": "source-mac", "text": "AA-AA-AA-AA-AA-AA"}, {"id": "gateway-mac", "text": "11-11-11-11-11-11"}, {"id": "remote-mac", "text": "MAC de 8.8.8.8"}],
        "correct_map": {"remote-ip": "ip", "source-mac": "source", "gateway-mac": "destination"},
        "feedback": {"gateway-ip": "O gateway recebe o primeiro frame, mas não substitui o destino IP final.", "remote-mac": "O primeiro frame da rede local é entregue ao gateway."},
        "misconceptions": {"gateway-ip": "confuses_gateway_with_final_ip_destination", "remote-mac": "confuses_remote_ip_with_destination_mac", "source-mac": "confuses_source_and_destination_mac", "gateway-mac": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Separe o destino IP remoto da primeira entrega Ethernet local.",
        "hint": "O IP continua remoto; Destination MAC pertence ao gateway.",
        "correct_feedback": "Correto. IP Destination permanece 8.8.8.8; Source MAC é AA-AA... e Destination MAC é 11-11....",
    },
    {
        "id": "5", "number": 5, "category": "Inferir", "difficulty_level": 4,
        "type": "terminal_analysis", "title": "Qual associação importa?", "primary": "MAC", "related": ["ARP", "FRAME"],
        "outputs": [{"title": "arp -a", "text": "192.168.10.1     11-11-11-11-11-11\n192.168.10.80    BB-BB-BB-BB-BB-BB\n192.168.10.90    CC-CC-CC-CC-CC-CC"}],
        "context_lines": ["Destino final: 8.8.8.8", "Gateway: 192.168.10.1"],
        "question": "Qual associação fornece o Destination MAC do primeiro frame?",
        "correct": "gateway", "options": [
            option("gateway", "192.168.10.1 → 11-11-11-11-11-11", "Correto. O primeiro frame é entregue ao gateway."),
            option("local80", "192.168.10.80 → BB-BB-BB-BB-BB-BB", "Essa associação pertence a outro host local, não ao gateway desta entrega remota.", "confuses_remote_ip_with_destination_mac"),
            option("local90", "192.168.10.90 → CC-CC-CC-CC-CC-CC", "Essa associação não corresponde ao próximo salto apresentado."),
        ],
    },
    {
        "id": "6", "number": 6, "category": "Inferir", "difficulty_level": 4,
        "type": "capture_analysis", "title": "Captura coerente?", "primary": "MAC", "related": ["FRAME"],
        "context_lines": ["PC-A · AA-AA-AA-AA-AA-AA", "Gateway · 11-11-11-11-11-11", "Destino final · 8.8.8.8"],
        "capture": "Ethernet\nSource: AA-AA-AA-AA-AA-AA\nDestination: 11-11-11-11-11-11\n\nIPv4\nSource: 192.168.10.25\nDestination: 8.8.8.8",
        "question": "A combinação é coerente?",
        "correct": "coherent", "options": [option("coherent", "SIM, É COERENTE", "A combinação é coerente."), option("incoherent", "NÃO, É INCOERENTE", "O destino IP pode continuar remoto enquanto Destination MAC pertence ao gateway.", "confuses_remote_ip_with_destination_mac")],
        "evidence_tokens": [{"id": "ip", "text": "Destination IP = 8.8.8.8"}, {"id": "mac", "text": "Destination MAC = 11-11-11-11-11-11"}, {"id": "source", "text": "Source IP = 192.168.10.25"}, {"id": "gateway-ip", "text": "Gateway IP = 192.168.10.1"}],
        "correct_evidence": ["ip", "mac"],
        "wrong_feedback": "Selecione as duas evidências: destino IP remoto e Destination MAC do gateway.",
        "hint": "Compare destino final com entrega Ethernet inicial.",
        "correct_feedback": "Correto. O destino IP é remoto e o primeiro Destination MAC pertence ao gateway.",
    },
    {
        "id": "7", "number": 7, "category": "Inferir", "difficulty_level": 4,
        "type": "find_inconsistency", "title": "Encontre o erro", "primary": "MAC", "related": ["ARP", "FRAME"],
        "context_lines": ["Destino local: 192.168.10.80", "ARP Cache: .80 → BB-BB-BB-BB-BB-BB", "11-11-11-11-11-11 = gateway"],
        "capture_fields": [
            option("source", "Source MAC · AA-AA-AA-AA-AA-AA", "Esse campo é coerente com a origem apresentada."),
            option("destination", "Destination MAC · 11-11-11-11-11-11", "Correto. Para o destino local .80, a associação disponível indica BB-BB..., não o MAC do gateway.", "confuses_remote_ip_with_destination_mac"),
            option("ip", "IPv4 Destination · 192.168.10.80", "Esse é o destino IPv4 local apresentado."),
        ],
        "question": "Qual campo torna o frame inconsistente?", "correct": "destination",
    },
    {
        "id": "8", "number": 8, "category": "Inferir", "difficulty_level": 4,
        "type": "evidence_sort", "title": "O que as evidências sustentam?", "primary": "MAC", "related": ["ARP", "FRAME"],
        "capture": "ARP Cache: .80 → BB-BB-BB-BB-BB-BB\n\nFrame\nSource: AA-AA-AA-AA-AA-AA\nDestination: BB-BB-BB-BB-BB-BB",
        "slots": [{"id": "supported", "label": "SUSTENTADO", "capacity": "many"}, {"id": "unsupported", "label": "NÃO SUSTENTADO", "capacity": "many"}],
        "tokens": [{"id": "known", "text": "O host possui associação para .80."}, {"id": "destination", "text": "O frame utiliza BB-BB... como Destination MAC."}, {"id": "source", "text": "O Source MAC apresentado é AA-AA...."}, {"id": "app", "text": "A aplicação funciona necessariamente."}, {"id": "tcp", "text": "TCP está estabelecido."}, {"id": "path", "text": "Todo o caminho está saudável."}],
        "correct_map": {"known": "supported", "destination": "supported", "source": "supported", "app": "unsupported", "tcp": "unsupported", "path": "unsupported"},
        "wrong_feedback": "Classifique somente o que aparece nas evidências; aplicação, TCP e caminho exigem outros dados.",
        "hint": "Separe observação direta de conclusão adicional.",
        "correct_feedback": "Correto. As evidências sustentam a associação e os dois campos MAC, mas não o restante da comunicação.",
    },
    {
        "id": "9", "number": 9, "category": "Diagnosticar", "difficulty_level": 5,
        "type": "diagnostic_map", "title": "O MAC parece certo, mas o ping falha", "primary": "MAC", "related": ["ARP", "FRAME"],
        "scenario": ["ARP Cache: .80 → BB-BB-BB-BB-BB-BB", "Frame: Source AA-AA... · Destination BB-BB...", "ping 192.168.10.80 falha", "DNS: 8.8.8.8", "CPU: 4%"],
        "slots": [{"id": "affirm", "label": "JÁ POSSO AFIRMAR", "capacity": "many"}, {"id": "less", "label": "FICA MENOS PROVÁVEL", "capacity": "many"}, {"id": "unknown", "label": "NÃO POSSO AFIRMAR", "capacity": "many"}],
        "tokens": [{"id": "association", "text": "Existe associação MAC para .80 e o frame usa esse MAC."}, {"id": "arp-less", "text": "Falha simples de descoberta do MAC via ARP."}, {"id": "all-ok", "text": "Toda a comunicação está funcionando."}, {"id": "dns", "text": "DNS necessariamente causa o problema."}, {"id": "cpu", "text": "CPU causa a perda."}],
        "correct_map": {"association": "affirm", "arp-less": "less", "all-ok": "unknown"},
        "feedback": {"dns": "O teste utiliza diretamente um IPv4; nada sustenta DNS como causa.", "cpu": "O valor de CPU não demonstra relação causal."},
        "wrong_feedback": "Use a associação e o frame como evidências sem concluir que toda a comunicação funciona.",
        "hint": "MAC e ARP parecem concluídos, mas isso não prova as etapas seguintes.",
        "correct_feedback": "Correto. A descoberta simples via ARP fica menos provável, mas a causa da falha continua não demonstrada.",
    },
    {
        "id": "10", "number": 10, "category": "Diagnosticar / Sintetizar", "difficulty_level": 5,
        "type": "integrated_concept_map", "title": "Sistema completo", "primary": "MAC", "related": ["ARP", "FRAME"],
        "slots": [{"id": "possesses", "label": "O HOST POSSUI", "capacity": "many"}, {"id": "needs", "label": "O FRAME PRECISA"}, {"id": "unknown", "label": "SE O MAC NÃO FOR CONHECIDO"}, {"id": "mechanism", "label": "MECANISMO UTILIZADO"}, {"id": "learned", "label": "INFORMAÇÃO APRENDIDA"}, {"id": "used", "label": "ONDE SERÁ UTILIZADA"}],
        "tokens": [{"id": "data", "text": "Dados"}, {"id": "source", "text": "Source MAC da própria interface"}, {"id": "needed", "text": "Destination MAC"}, {"id": "resolve", "text": "Resolver a informação"}, {"id": "arp", "text": "ARP"}, {"id": "mac", "text": "Endereço MAC"}, {"id": "destination", "text": "Destination MAC do frame"}, {"id": "dns", "text": "DNS"}, {"id": "tcp", "text": "Porta TCP"}, {"id": "switch", "text": "Porta do switch"}],
        "correct_map": {"data": "possesses", "source": "possesses", "needed": "needs", "resolve": "unknown", "arp": "mechanism", "mac": "learned", "destination": "used"},
        "feedback": {"dns": "DNS não fornece o MAC necessário quando o IPv4 já é conhecido.", "tcp": "Porta TCP não é um endereço Ethernet.", "switch": "MAC não é a porta física do switch."},
        "misconceptions": {"dns": "confuses_mac_with_arp", "tcp": "confuses_mac_with_transport_port", "switch": "confuses_mac_with_switch_port", "arp": "confuses_mac_with_arp"},
        "wrong_feedback": "Reconstrua: dados e Source MAC, Destination MAC necessário, ARP se preciso, MAC aprendido e uso no frame.",
        "hint": "DADOS → FRAME → SOURCE + DESTINATION → ARP SE NECESSÁRIO → MAC → TRANSMISSÃO.",
        "correct_feedback": "Correto. DADOS → FRAME → SOURCE MAC + DESTINATION MAC → ARP SE NECESSÁRIO → MAC → TRANSMISSÃO.",
        "free_question": "Explique com suas palavras qual é o papel do endereço MAC em um frame Ethernet e como ARP pode participar desse processo.",
        "reference": "O frame Ethernet utiliza endereços MAC de origem e destino para realizar a entrega de Camada 2. O Source MAC representa a origem daquele frame e o Destination MAC representa para quem a entrega Ethernet está sendo feita. Quando o host conhece o IPv4 relevante, mas ainda não conhece o MAC necessário, ARP pode descobrir essa associação para que o endereço seja utilizado no frame.",
        "reference_note": "Compare as ideias, sem precisar usar exatamente as mesmas palavras.",
    },
]


ACTIVITY_MAP = {activity["id"]: activity for activity in ACTIVITIES}
CAPABILITIES = ["Montar entrega local", "Inverter direção", "Cruzar ferramentas", "Separar local e remoto", "Ler ARP Cache", "Analisar captura", "Detectar inconsistência", "Analisar evidências", "Diagnosticar", "Sintetizar"]
MISCONCEPTION_LABELS = {
    "confuses_mac_with_ip": "MAC × IPv4",
    "confuses_mac_with_arp": "MAC × ARP",
    "confuses_mac_with_switch_port": "MAC × porta do switch",
    "confuses_mac_with_transport_port": "MAC × porta de transporte",
    "confuses_source_and_destination_mac": "Source MAC × Destination MAC",
    "confuses_remote_ip_with_destination_mac": "Destino remoto × Destination MAC",
    "confuses_gateway_with_final_ip_destination": "Gateway × destino IP final",
}
