"""Structured content for the 20-activity MAC Address practice session."""


def option(key, text, feedback, misconception_code=None):
    return {
        "key": key,
        "text": text,
        "feedback": feedback,
        "misconception_code": misconception_code,
    }


ACTIVITIES = [
    {
        "id": "1", "number": 1, "category": "Reconhecer", "difficulty_level": 1,
        "type": "visual_selection", "title": "Qual deles é um endereço MAC?",
        "instruction": "Selecione somente o valor que possui o formato típico de um endereço MAC.",
        "correct": "mac",
        "options": [
            option("ipv4", "192.168.10.25", "Esse valor possui o formato de um endereço IPv4 em notação decimal.", "confuses_mac_with_ip"),
            option("mac", "AA:BB:CC:DD:EE:FF", "Correto. O endereço apresentado possui seis grupos de dois dígitos hexadecimais."),
            option("port", "443", "`443` pode representar uma porta de transporte, não um endereço MAC.", "confuses_mac_with_transport_port"),
            option("mask", "255.255.255.0", "Esse valor possui formato típico de uma máscara IPv4 decimal.", "confuses_mac_with_ip"),
        ],
    },
    {
        "id": "2", "number": 2, "category": "Reconhecer / Relacionar", "difficulty_level": 2,
        "type": "find_inconsistency", "title": "Um deles não combina",
        "question": "Considerando somente o formato estudado para endereços MAC, clique no valor que pertence claramente a outro tipo de endereçamento.",
        "correct": "ipv4", "options": [
            option("mac1", "AA:BB:CC:DD:EE:FF", "Esse valor possui o formato estudado para endereços MAC."),
            option("mac2", "11:22:33:44:55:66", "Esse valor possui o formato estudado para endereços MAC."),
            option("mac3", "AB-CD-EF-12-34-56", "Esse valor representa um endereço MAC usando outro separador."),
            option("ipv4", "192.168.10.80", "Esse valor está em formato IPv4. Os demais representam endereços MAC usando separadores diferentes.", "confuses_mac_with_ip"),
        ],
    },
    {
        "id": "3", "number": 3, "category": "Relacionar", "difficulty_level": 2,
        "type": "frame_hotspot", "title": "Source ou Destination?",
        "context_lines": ["PC-A · MAC AA:AA:AA:AA:AA:AA", "PC-B · MAC BB:BB:BB:BB:BB:BB"],
        "question": "PC-B recebeu esse frame. Clique no campo que permite identificar qual interface originou a transmissão Ethernet.",
        "frame_note": "Representação simplificada para focar nos campos de endereço que estamos estudando.",
        "correct": "source", "options": [
            option("destination", "Destination MAC\nBB:BB:BB:BB:BB:BB", "Esse campo identifica para qual endereço Ethernet o frame está sendo entregue. Para identificar quem o originou, observe o campo de origem.", "confuses_source_and_destination_mac"),
            option("source", "Source MAC\nAA:AA:AA:AA:AA:AA", "Correto. `Source MAC` identifica a origem Ethernet do frame."),
            option("data", "DATA\n...", "Os dados transportados não substituem o campo que identifica a origem Ethernet do frame."),
        ],
    },
    {
        "id": "4", "number": 4, "category": "Reconstruir", "difficulty_level": 2,
        "type": "sentence_repair", "title": "Source e Destination foram invertidos",
        "incorrect_sentence": "PC-A envia um frame para PC-B. O Source MAC deve conter o MAC de PC-B e o Destination MAC deve conter o MAC de PC-A.",
        "slots": [{"id": "source", "label": "Source MAC"}, {"id": "destination", "label": "Destination MAC"}],
        "tokens": [{"id": "pc-a", "text": "MAC de PC-A"}, {"id": "pc-b", "text": "MAC de PC-B"}],
        "correct_map": {"pc-a": "source", "pc-b": "destination"},
        "feedback_by_token_slot": {"pc-b:source": "O `Source MAC` representa quem está originando o frame. Neste cenário, quem envia é PC-A."},
        "misconceptions": {"pc-a": "confuses_source_and_destination_mac", "pc-b": "confuses_source_and_destination_mac"},
        "wrong_feedback": "O `Source MAC` representa quem está originando o frame. Neste cenário, quem envia é PC-A.",
        "correct_feedback": "Correto. Origem Ethernet = PC-A; destino Ethernet = PC-B.",
    },
    {
        "id": "5", "number": 5, "category": "Aplicar", "difficulty_level": 3,
        "type": "frame_builder", "title": "Monte os endereços do frame",
        "context_lines": ["PC-A · IPv4: 192.168.10.25 · MAC: AA:AA:AA:AA:AA:AA", "PC-B · IPv4: 192.168.10.80 · MAC: BB:BB:BB:BB:BB:BB"],
        "situation": "PC-A enviará um frame Ethernet diretamente para PC-B.",
        "frame_note": "Representação simplificada para focar nos campos de endereço que estamos estudando.",
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "mac-a", "text": "AA:AA:AA:AA:AA:AA"}, {"id": "mac-b", "text": "BB:BB:BB:BB:BB:BB"}, {"id": "ip-a", "text": "192.168.10.25"}, {"id": "ip-b", "text": "192.168.10.80"}],
        "correct_map": {"mac-a": "source", "mac-b": "destination"},
        "feedback": {"ip-a": "Esse campo do frame espera um endereço MAC, não um endereço IPv4.", "ip-b": "Esse campo do frame espera um endereço MAC, não um endereço IPv4."},
        "misconceptions": {"ip-a": "confuses_mac_with_ip", "ip-b": "confuses_mac_with_ip", "mac-a": "confuses_source_and_destination_mac", "mac-b": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Verifique quem está enviando e quem deverá receber a entrega Ethernet.",
        "correct_feedback": "Correto. PC-A é a origem Ethernet e PC-B é o destino dessa entrega local.",
    },
    {
        "id": "6", "number": 6, "category": "Aplicar", "difficulty_level": 3,
        "type": "topology_hotspot", "title": "O switch é o destino?", "topology": "mac-local",
        "question": "PC-A está enviando um frame diretamente para PC-B. Clique no dispositivo cujo MAC deverá aparecer como `Destination MAC`.",
        "correct": "pc-b", "options": [
            option("pc-a", "PC-A\nAA:AA:AA:AA:AA:AA", "PC-A é o emissor e fornece o Source MAC.", "confuses_source_and_destination_mac"),
            option("switch", "SWITCH", "O switch encaminha o frame pelo caminho local, mas não se torna o endereço de destino só porque o frame passa fisicamente por ele.", "confuses_mac_with_switch_port"),
            option("pc-b", "PC-B\nBB:BB:BB:BB:BB:BB", "Correto. O frame é endereçado a PC-B; o switch participa do encaminhamento."),
        ],
        "after": "O switch encaminha o frame dentro da LAN. O funcionamento interno dessa decisão será estudado posteriormente.",
    },
    {
        "id": "7", "number": 7, "category": "Inferir", "difficulty_level": 4,
        "type": "frame_builder", "title": "Primeiro frame para destino remoto",
        "context_lines": ["PC-A · IPv4: 192.168.10.25 · MAC: AA:AA:AA:AA:AA:AA", "Gateway · IPv4: 192.168.10.1 · MAC: 11:11:11:11:11:11", "Destino final: 8.8.8.8"],
        "instruction": "Complete somente os endereços Ethernet do PRIMEIRO frame enviado por PC-A.",
        "frame_note": "Representação simplificada para focar nos campos de endereço que estamos estudando.",
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "mac-a", "text": "AA:AA:AA:AA:AA:AA"}, {"id": "gateway-mac", "text": "11:11:11:11:11:11"}, {"id": "remote-mac", "text": "MAC de 8.8.8.8"}],
        "correct_map": {"mac-a": "source", "gateway-mac": "destination"},
        "feedback": {"remote-mac": "`8.8.8.8` é o destino IP final, mas está fora da rede local. O primeiro frame precisa ser entregue ao gateway."},
        "misconceptions": {"remote-mac": "confuses_remote_ip_with_destination_mac", "gateway-mac": "confuses_source_and_destination_mac", "mac-a": "confuses_source_and_destination_mac"},
        "wrong_feedback": "PC-A continua sendo a origem Ethernet. Para o Destination MAC, identifique quem recebe o primeiro frame na rede local.",
        "correct_feedback": "Correto. PC-A continua sendo a origem Ethernet, enquanto o gateway é o destino Ethernet do primeiro salto local.",
    },
    {
        "id": "8", "number": 8, "category": "Inferir", "difficulty_level": 4,
        "type": "dual_concept_map", "title": "Destino IP e destino Ethernet",
        "context_lines": ["PC-A: 192.168.10.25", "Gateway: 192.168.10.1 · MAC: 11:11:11:11:11:11", "Destino: 8.8.8.8"],
        "slots": [{"id": "final-ip", "label": "DESTINO IP FINAL"}, {"id": "first-mac", "label": "DESTINATION MAC DO PRIMEIRO FRAME"}],
        "tokens": [{"id": "remote-ip", "text": "8.8.8.8"}, {"id": "gateway-ip", "text": "192.168.10.1"}, {"id": "gateway-mac", "text": "11:11:11:11:11:11"}, {"id": "remote-mac", "text": "MAC de 8.8.8.8"}],
        "correct_map": {"remote-ip": "final-ip", "gateway-mac": "first-mac"},
        "feedback_by_token_slot": {"gateway-ip:final-ip": "O gateway é o próximo salto local, mas não substitui o destino IP final da comunicação.", "remote-mac:first-mac": "O primeiro frame Ethernet da LAN não é entregue diretamente ao host remoto."},
        "feedback": {"gateway-ip": "O gateway é o próximo salto local, mas não substitui o destino IP final da comunicação.", "remote-mac": "O primeiro frame Ethernet da LAN não é entregue diretamente ao host remoto."},
        "misconceptions": {"gateway-ip": "confuses_gateway_with_final_ip_destination", "remote-mac": "confuses_remote_ip_with_destination_mac"},
        "wrong_feedback": "Separe o destino final da comunicação do dispositivo que recebe o primeiro frame na LAN.",
        "correct_feedback": "Correto. O IP continua apontando para o destino remoto, enquanto o MAC identifica o próximo dispositivo que receberá o frame localmente.",
    },
    {
        "id": "9", "number": 9, "category": "Ferramenta", "difficulty_level": 1,
        "type": "terminal_hotspot", "title": "Encontre seu próprio MAC",
        "terminal_heading": "C:\\> ipconfig /all\n\nAdaptador Ethernet Ethernet:",
        "terminal_columns": ["Informação", "Valor"], "terminal_rows": [
            [option("physical-label", "Endereço Físico", "Clique no valor correspondente a esta informação."), option("physical", "AA-BB-CC-DD-EE-FF", "Correto. No Windows, `Endereço Físico` representa o MAC da interface.")],
            [option("dhcp-label", "DHCP Habilitado", "Essa configuração não representa o endereço MAC."), option("dhcp", "Sim", "Esse valor indica o estado do DHCP, não o MAC da interface.")],
            [option("ipv4-label", "Endereço IPv4", "Clique no valor correspondente para avaliar esse endereço."), option("ipv4", "192.168.10.25", "Esse é o endereço lógico IPv4 da interface, não seu endereço físico Ethernet.", "confuses_mac_with_ip")],
            [option("mask-label", "Máscara de Sub-rede", "Essa informação não representa o endereço MAC."), option("mask", "255.255.255.0", "Esse valor representa a máscara IPv4 da interface.")],
            [option("gateway-label", "Gateway Padrão", "Clique no valor correspondente para avaliar esse endereço."), option("gateway", "192.168.10.1", "Esse é o endereço IPv4 do gateway configurado.")],
        ],
        "question": "Clique na informação que representa o endereço MAC da própria interface Ethernet.", "correct": "physical",
    },
    {
        "id": "10", "number": 10, "category": "Interpretar", "difficulty_level": 3,
        "type": "command_match", "title": "Qual ferramenta responde?",
        "slots": [{"id": "own", "label": "Quero descobrir o MAC da minha própria interface Ethernet"}, {"id": "known", "label": "Quero saber qual MAC meu computador conhece para 192.168.10.80"}],
        "tokens": [{"id": "ipconfig", "text": "ipconfig /all"}, {"id": "arp", "text": "arp -a"}],
        "correct_map": {"ipconfig": "own", "arp": "known"},
        "wrong_feedback": "As duas ferramentas podem mostrar MACs, mas respondem a perguntas diferentes.",
        "correct_feedback": "Correto. `ipconfig /all` mostra informações da própria interface; `arp -a` mostra associações IPv4 → MAC conhecidas pelo host.",
    },
    {
        "id": "11", "number": 11, "category": "Interpretar / Inferir", "difficulty_level": 4,
        "type": "compare_outputs_builder", "title": "Cruze duas saídas",
        "outputs": [
            {"title": "ipconfig /all", "text": "Endereço IPv4: 192.168.10.25\nEndereço Físico: AA-BB-CC-DD-EE-FF"},
            {"title": "arp -a", "text": "Internet Address      Physical Address\n192.168.10.1          11-11-11-11-11-11\n192.168.10.80         BB-BB-BB-BB-BB-BB"},
        ],
        "situation": "PC-A enviará um frame para `192.168.10.80`.",
        "slots": [{"id": "source", "label": "SOURCE MAC"}, {"id": "destination", "label": "DESTINATION MAC"}],
        "tokens": [{"id": "own", "text": "AA-BB-CC-DD-EE-FF"}, {"id": "gateway", "text": "11-11-11-11-11-11"}, {"id": "local", "text": "BB-BB-BB-BB-BB-BB"}],
        "correct_map": {"own": "source", "local": "destination"},
        "feedback": {"gateway": "Existe uma entrada para o gateway, mas o destino informado pertence diretamente à rede local estudada. A associação relevante é a do próprio destino."},
        "misconceptions": {"gateway": "confuses_gateway_with_final_ip_destination", "own": "confuses_source_and_destination_mac", "local": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Cruze o MAC da própria interface com a associação ARP do destino local.",
        "correct_feedback": "Correto. Foi necessário cruzar o MAC da própria interface com a associação ARP do destino.",
    },
    {
        "id": "12", "number": 12, "category": "Inferir", "difficulty_level": 4,
        "type": "compare_outputs_builder", "title": "Destino remoto com duas saídas",
        "outputs": [
            {"title": "ipconfig /all", "text": "IPv4: 192.168.10.25\nPhysical Address: AA-BB-CC-DD-EE-FF\nGateway: 192.168.10.1"},
            {"title": "arp -a", "text": "192.168.10.1   11-11-11-11-11-11\n192.168.10.80  BB-BB-BB-BB-BB-BB"},
        ],
        "context_lines": ["Destino final: 8.8.8.8"],
        "slots": [{"id": "source", "label": "SOURCE MAC DO PRIMEIRO FRAME"}, {"id": "destination", "label": "DESTINATION MAC DO PRIMEIRO FRAME"}],
        "tokens": [{"id": "own", "text": "AA-BB-CC-DD-EE-FF"}, {"id": "gateway", "text": "11-11-11-11-11-11"}, {"id": "local80", "text": "BB-BB-BB-BB-BB-BB"}],
        "correct_map": {"own": "source", "gateway": "destination"},
        "feedback": {"local80": "Essa entrada pertence a outro host local. Para o destino remoto, o primeiro frame precisa ser entregue ao gateway."},
        "misconceptions": {"local80": "confuses_remote_ip_with_destination_mac", "own": "confuses_source_and_destination_mac", "gateway": "confuses_source_and_destination_mac"},
        "wrong_feedback": "Use `ipconfig /all` para identificar a origem e a entrada ARP do gateway para o destino Ethernet local.",
        "correct_feedback": "Correto. `ipconfig /all` fornece o Source MAC da interface e `arp -a` fornece o MAC já conhecido para o gateway.",
    },
    {
        "id": "13", "number": 13, "category": "Integrar", "difficulty_level": 3,
        "type": "process_builder", "title": "O MAC ainda está faltando", "concept_badge": "MAC + ARP",
        "context_lines": ["PC-A conhece o destino IPv4: 192.168.10.80", "Destino MAC: ???", "A ARP Cache inicialmente não possui 192.168.10.80"],
        "slots": [{"id": "step1", "label": "1"}, {"id": "step2", "label": "2"}, {"id": "step3", "label": "3"}, {"id": "step4", "label": "4"}, {"id": "step5", "label": "5"}],
        "tokens": [{"id": "cache", "text": "Consultar ARP Cache"}, {"id": "request", "text": "ARP Request"}, {"id": "reply", "text": "ARP Reply"}, {"id": "learn", "text": "MAC aprendido"}, {"id": "frame", "text": "Montar frame Ethernet"}, {"id": "dns", "text": "DNS Request"}, {"id": "tcp", "text": "TCP handshake"}],
        "correct_map": {"cache": "step1", "request": "step2", "reply": "step3", "learn": "step4", "frame": "step5"},
        "feedback": {"dns": "O IPv4 já é conhecido. Não estamos tentando resolver um nome.", "tcp": "Antes de raciocinar sobre uma sessão de transporte, ainda falta o endereço necessário para a entrega Ethernet local."},
        "misconceptions": {"dns": "confuses_mac_with_arp", "tcp": "confuses_mac_with_transport_port"},
        "wrong_feedback": "ARP precisa produzir o MAC antes que esse endereço possa ser utilizado no frame.",
        "correct_feedback": "Correto. ARP resolve a informação que faltava e o MAC aprendido passa a poder ser utilizado no frame.",
    },
    {
        "id": "14", "number": 14, "category": "Integrar", "difficulty_level": 3,
        "type": "concept_relation_builder", "title": "Qual é a entrada e qual é a saída?", "concept_badge": "ARP",
        "slots": [{"id": "known", "label": "INFORMAÇÃO JÁ CONHECIDA"}, {"id": "discover", "label": "INFORMAÇÃO QUE PRECISO DESCOBRIR"}],
        "tokens": [{"id": "ipv4", "text": "IPv4 local relevante"}, {"id": "mac", "text": "MAC necessário"}, {"id": "tcp", "text": "porta TCP"}, {"id": "dns", "text": "nome DNS"}, {"id": "switch", "text": "porta do switch"}],
        "correct_map": {"ipv4": "known", "mac": "discover"},
        "feedback": {"tcp": "Uma porta TCP não é a informação resolvida por ARP.", "dns": "ARP parte de um IPv4 conhecido; não resolve um nome DNS.", "switch": "ARP não descobre uma porta do switch."},
        "misconceptions": {"tcp": "confuses_mac_with_transport_port", "dns": "confuses_mac_with_arp", "switch": "confuses_mac_with_switch_port"},
        "wrong_feedback": "Separe a informação que já inicia o processo da informação que ARP precisa fornecer.",
        "correct_feedback": "Correto.\n\nIPv4 conhecido\n↓\nARP\n↓\nMAC necessário\n↓\nDestination MAC do frame",
    },
    {
        "id": "15", "number": 15, "category": "Diferenciar", "difficulty_level": 3,
        "type": "role_sort", "title": "Endereço ou mecanismo?", "concept_badge": "MAC + ARP",
        "slots": [{"id": "information", "label": "ENDEREÇO / INFORMAÇÃO", "capacity": "many"}, {"id": "process", "label": "MECANISMO / PROCESSO", "capacity": "many"}, {"id": "field", "label": "CAMPO DO FRAME", "capacity": "many"}],
        "tokens": [{"id": "mac", "text": "BB:BB:BB:BB:BB:BB"}, {"id": "request", "text": "ARP Request"}, {"id": "reply", "text": "ARP Reply"}, {"id": "source", "text": "Source MAC"}, {"id": "destination", "text": "Destination MAC"}, {"id": "ipv4", "text": "192.168.10.80"}],
        "correct_map": {"mac": "information", "ipv4": "information", "request": "process", "reply": "process", "source": "field", "destination": "field"},
        "misconceptions": {"request": "confuses_mac_with_arp", "reply": "confuses_mac_with_arp", "source": "confuses_mac_with_arp", "destination": "confuses_mac_with_arp"},
        "wrong_feedback": "MAC, IPv4, ARP e campos do frame estão relacionados, mas não representam a mesma categoria de coisa.",
        "correct_feedback": "Correto. MAC, IPv4, ARP e campos do frame estão relacionados, mas não representam a mesma categoria de coisa.",
    },
    {
        "id": "16", "number": 16, "category": "Integrar", "difficulty_level": 4,
        "type": "integrated_flow_builder", "title": "Da intenção ao frame", "concept_badge": "MAC + ARP",
        "context_lines": ["PC-A · IPv4: 192.168.10.25 · MAC: AA:AA:AA:AA:AA:AA", "PC-B · IPv4: 192.168.10.80 · MAC: BB:BB:BB:BB:BB:BB", "ARP Cache: sem entrada para PC-B"],
        "items": ["Envia ARP Request", "PC-A conhece o IPv4 de PC-B", "PC-A aprende BB:BB:BB:BB:BB:BB", "Consulta ARP Cache", "Envia frame", "PC-B envia ARP Reply", "Não encontra associação", "Monta frame: Source AA... Destination BB..."],
        "correct_order": ["PC-A conhece o IPv4 de PC-B", "Consulta ARP Cache", "Não encontra associação", "Envia ARP Request", "PC-B envia ARP Reply", "PC-A aprende BB:BB:BB:BB:BB:BB", "Monta frame: Source AA... Destination BB...", "Envia frame"],
        "wrong_feedback": "Algumas etapas estão fora de ordem. Pense primeiro no que PC-A já conhece e em qual informação precisa estar disponível antes do frame poder ser endereçado.",
        "hint": "O frame só pode receber `Destination MAC = BB...` depois que esse MAC tiver sido aprendido.",
        "correct_feedback": "Correto. ARP não é a entrega final dos dados; ele fornece a informação necessária para a entrega Ethernet seguinte.",
    },
    {
        "id": "17", "number": 17, "category": "Integrar / Inferir", "difficulty_level": 4,
        "type": "integrated_flow_builder", "title": "Construa a comunicação remota", "concept_badge": "MAC + ARP",
        "context_lines": ["PC-A · IPv4: 192.168.10.25 · MAC: AA:AA:AA:AA:AA:AA", "Gateway · IPv4: 192.168.10.1 · MAC: 11:11:11:11:11:11", "Destino final: 8.8.8.8", "ARP Cache: sem entrada para o gateway"],
        "items": ["Gateway responde com 11:11:11:11:11:11", "PC-A identifica que o destino final é remoto", "Frame é entregue ao gateway", "ARP procura 192.168.10.1", "PC-A aprende o MAC do gateway", "O primeiro frame precisa ser entregue ao gateway", "PC-A monta o primeiro frame: IP destino = 8.8.8.8 e Destination MAC = 11:11:11:11:11:11"],
        "correct_order": ["PC-A identifica que o destino final é remoto", "O primeiro frame precisa ser entregue ao gateway", "ARP procura 192.168.10.1", "Gateway responde com 11:11:11:11:11:11", "PC-A aprende o MAC do gateway", "PC-A monta o primeiro frame: IP destino = 8.8.8.8 e Destination MAC = 11:11:11:11:11:11", "Frame é entregue ao gateway"],
        "wrong_feedback": "O destino final é remoto. A resolução ARP local deve ocorrer para o próximo salto, o gateway.",
        "hint": "O IP continua identificando 8.8.8.8, mas o primeiro frame precisa do MAC do gateway.",
        "correct_feedback": "Correto. O IP identifica o destino final, enquanto o MAC do primeiro frame identifica o próximo dispositivo alcançável localmente.",
        "wrong_order_misconception": "confuses_remote_ip_with_destination_mac",
    },
    {
        "id": "18", "number": 18, "category": "Diagnosticar", "difficulty_level": 4,
        "type": "evidence_sort", "title": "A resolução ARP já terminou?", "concept_badge": "MAC + ARP",
        "scenario": ["PC-A: 192.168.10.25", "Destino local: 192.168.10.80"],
        "capture": "Who has 192.168.10.80?\nTell 192.168.10.25\n\n192.168.10.80 is at\nBB:BB:BB:BB:BB:BB\n\nC:\\> arp -a\n\n192.168.10.80\nBB-BB-BB-BB-BB-BB",
        "slots": [{"id": "supported", "label": "SUSTENTADO PELAS EVIDÊNCIAS", "capacity": "many"}, {"id": "unsupported", "label": "NÃO SUSTENTADO", "capacity": "many"}],
        "tokens": [{"id": "complete", "text": "A resolução ARP apresentada foi concluída."}, {"id": "known", "text": "PC-A conhece um MAC associado a 192.168.10.80."}, {"id": "arp-problem", "text": "O problema de comunicação é necessariamente ARP."}, {"id": "tcp", "text": "Existe necessariamente uma conexão TCP funcionando."}, {"id": "usable", "text": "O MAC BB:BB:BB:BB:BB:BB pode ser utilizado como Destination MAC para uma entrega local a 192.168.10.80."}],
        "correct_map": {"complete": "supported", "known": "supported", "usable": "supported", "arp-problem": "unsupported", "tcp": "unsupported"},
        "wrong_feedback": "Descobrir o MAC resolve uma etapa específica da comunicação. Isso não prova, sozinho, que todas as etapas posteriores estejam funcionando.",
        "correct_feedback": "Correto. Descobrir o MAC resolve uma etapa específica da comunicação. Isso não prova, sozinho, que todas as etapas posteriores estejam funcionando.",
    },
    {
        "id": "19", "number": 19, "category": "Diagnosticar", "difficulty_level": 5,
        "type": "diagnostic_map", "title": "O que essa evidência muda?", "concept_badge": "MAC + ARP",
        "scenario": ["PC-A: 192.168.10.25", "Destino local: 192.168.10.80", "ARP Cache: 192.168.10.80 → BB-BB-BB-BB-BB-BB", "Source MAC: AA-AA-AA-AA-AA-AA", "Destination MAC: BB-BB-BB-BB-BB-BB", "O ping para 192.168.10.80 ainda falha.", "DNS configurado: 8.8.8.8", "CPU: 7%"],
        "slots": [{"id": "affirm", "label": "O QUE JÁ POSSO AFIRMAR"}, {"id": "less", "label": "O QUE FICA MENOS PROVÁVEL"}, {"id": "unknown", "label": "O QUE NÃO POSSO CONCLUIR"}],
        "tokens": [{"id": "addressing", "text": "PC-A possui uma associação MAC para o destino e está endereçando o frame com esse MAC."}, {"id": "arp-less", "text": "Falha na descoberta ARP do endereço de destino."}, {"id": "all-ok", "text": "Toda a comunicação funciona corretamente só porque ARP funcionou."}, {"id": "dns", "text": "DNS é necessariamente a causa."}, {"id": "cpu", "text": "CPU de 7% está causando perda de frames."}, {"id": "arp-still", "text": "ARP necessariamente continua sendo o problema."}],
        "correct_map": {"addressing": "affirm", "arp-less": "less", "all-ok": "unknown"},
        "feedback": {"dns": "O teste utiliza diretamente um IPv4 e já temos evidência de resolução MAC. Nada apresentado aponta especificamente para DNS.", "cpu": "O valor apresentado não fornece evidência de relação causal com o problema.", "arp-still": "A associação e o endereçamento do frame tornam menos provável uma falha na descoberta ARP do destino."},
        "wrong_feedback": "Use as evidências para separar o que já está demonstrado, o que ficou menos provável e o que ainda não pode ser concluído.",
        "correct_feedback": "Correto. Uma investigação eficiente também consiste em usar evidências para reduzir a probabilidade de determinadas hipóteses.",
    },
    {
        "id": "20", "number": 20, "category": "Síntese", "difficulty_level": 4,
        "type": "concept_map_builder", "title": "Junte MAC e ARP", "concept_badge": "MAC + ARP",
        "slots": [{"id": "known", "label": "O HOST JÁ CONHECE"}, {"id": "needs", "label": "O HOST PRECISA DESCOBRIR"}, {"id": "mechanism", "label": "O MECANISMO UTILIZADO"}, {"id": "learned", "label": "A INFORMAÇÃO APRENDIDA"}, {"id": "used", "label": "ONDE ESSA INFORMAÇÃO SERÁ USADA"}],
        "tokens": [{"id": "ipv4", "text": "IPv4 relevante"}, {"id": "needed-mac", "text": "MAC necessário localmente"}, {"id": "arp", "text": "ARP"}, {"id": "mac", "text": "Endereço MAC"}, {"id": "destination", "text": "Destination MAC do frame"}, {"id": "dns", "text": "DNS"}, {"id": "tcp", "text": "porta TCP"}, {"id": "switch", "text": "porta do switch"}],
        "correct_map": {"ipv4": "known", "needed-mac": "needs", "arp": "mechanism", "mac": "learned", "destination": "used"},
        "feedback": {"dns": "O IPv4 relevante já é conhecido; DNS não é o mecanismo desta relação.", "tcp": "Uma porta TCP não é o endereço Ethernet necessário ao frame.", "switch": "A porta do switch não é a informação descoberta por ARP."},
        "misconceptions": {"dns": "confuses_mac_with_arp", "tcp": "confuses_mac_with_transport_port", "switch": "confuses_mac_with_switch_port", "arp": "confuses_mac_with_arp"},
        "wrong_feedback": "Separe a informação — MAC — do mecanismo que pode descobri-la — ARP — e indique onde o MAC será utilizado.",
        "correct_feedback": "Correto.\n\nIPv4 conhecido\n↓\nARP\n↓\nMAC aprendido\n↓\nDestination MAC\n↓\nFRAME ETHERNET",
        "free_question": "Explique com suas próprias palavras a diferença entre MAC e ARP e como os dois aparecem na mesma comunicação.",
        "reference": "MAC é um tipo de endereço utilizado nos frames Ethernet para identificar a origem e o destino da entrega local. ARP é um mecanismo que pode descobrir qual endereço MAC corresponde a um IPv4 conhecido no alcance local. Depois que o MAC necessário é aprendido, ele pode ser utilizado como Destination MAC no frame Ethernet.",
        "reference_note": "Sua explicação não precisa usar exatamente essas palavras. O importante é separar claramente a informação — MAC — do mecanismo que pode descobri-la — ARP.",
    },
]


ACTIVITY_MAP = {activity["id"]: activity for activity in ACTIVITIES}
CAPABILITIES = [
    "Reconhecer MAC", "Interpretar Source/Destination", "Construir frames",
    "Interpretar comandos", "Cruzar evidências", "Integrar MAC + ARP",
    "Raciocinar local × remoto", "Diagnosticar", "Explicar",
]
MISCONCEPTION_LABELS = {
    "confuses_mac_with_ip": "MAC × IPv4",
    "confuses_mac_with_arp": "MAC × ARP",
    "confuses_mac_with_switch_port": "MAC × porta do switch",
    "confuses_mac_with_transport_port": "MAC × porta de transporte",
    "confuses_source_and_destination_mac": "Source MAC × Destination MAC",
    "confuses_remote_ip_with_destination_mac": "Destino remoto × MAC do gateway",
    "confuses_gateway_with_final_ip_destination": "Gateway × destino IP final",
}
