"""Structured checkpoint content for Routing Table and route selection."""


def field(name, label, options=None):
    return {"name": name, "label": label, "options": options or []}


HINTS = [
    "Primeiro identifique quais prefixos realmente contêm o Destination IP.",
    "Depois, compare somente as rotas compatíveis e escolha o prefixo mais longo.",
]

ACTIVITIES = [
    {"id":"1","number":1,"category":"Aplicar","difficulty_level":3,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["IPv4","Next Hop"],"title":"Ler uma rota","scenario":"192.168.20.0/24 via 10.0.0.2 interface WAN1","instruction":"Identifique os três campos da rota.","fields":[field("prefix","Destination Prefix"),field("hop","Next Hop"),field("interface","Interface")],"correct_map":{"prefix":"192.168.20.0/24","hop":"10.0.0.2","interface":"wan1"},"feedback":{"prefix":"É o conjunto de destinos descrito pela rota.","hop":"É o próximo equipamento de Camada 3.","interface":"É a saída local."},"misconceptions":{"prefix":"confuses_destination_prefix_with_next_hop","hop":"confuses_next_hop_with_final_destination"},"wrong_feedback":"Separe o conjunto de destinos, o próximo roteador e a saída local.","correct_feedback":"Correto. A rota descreve o prefixo 192.168.20.0/24, via 10.0.0.2, pela WAN1.","hints":[]},
    {"id":"2","number":2,"category":"Classificar","difficulty_level":3,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["Next Hop"],"title":"Direct ou via Next Hop","scenario":"192.168.10.0/24 DIRECT LAN · 192.168.20.0/24 via 10.0.0.2 WAN1","instruction":"Classifique cada rota.","fields":[field("local","192.168.10.0/24",["DIRECT","VIA NEXT HOP"]),field("remote","192.168.20.0/24",["DIRECT","VIA NEXT HOP"])],"correct_map":{"local":"direct","remote":"via next hop"},"feedback":{"local":"Não há roteador intermediário.","remote":"10.0.0.2 é um próximo salto explícito."},"misconceptions":{"local":"assumes_every_route_requires_next_hop","remote":"ignores_directly_connected_route"},"wrong_feedback":"Observe se a linha informa outro roteador ou diz DIRECT.","correct_feedback":"Correto. A LAN é diretamente conectada; a rede 192.168.20.0/24 exige o next hop.","hints":[]},
    {"id":"3","number":3,"category":"Inferir","difficulty_level":4,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["IPv4","Subnet"],"title":"Escolher o caminho específico","scenario":"192.168.10.0/24 → LAN · 192.168.20.0/24 → R2 · 0.0.0.0/0 → R3 · Destino 192.168.20.80","instruction":"Qual caminho é selecionado?","fields":[field("path","Caminho",["LAN","R2","R3"])],"correct_map":{"path":"r2"},"feedback":{"path":"A rota padrão pode alcançar esse destino, mas verifique se existe uma rota que descreve o destino de forma mais específica."},"misconceptions":{"path":"assumes_default_route_has_priority"},"wrong_feedback":"Compare os prefixos das rotas que realmente correspondem ao Destination IP.","correct_feedback":"Correto. 192.168.20.0/24 vence a rota padrão e indica R2.","hints":[]},
    {"id":"4","number":4,"category":"Inferir","difficulty_level":4,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["Gateway"],"title":"Usar a rota padrão","scenario":"192.168.10.0/24 → LAN · 192.168.20.0/24 → R2 · 0.0.0.0/0 → R3 · Destino 8.8.8.8","instruction":"Qual prefixo será selecionado?","fields":[field("route","Rota")],"correct_map":{"route":"0.0.0.0/0"},"feedback":{"route":"Nenhuma das /24 contém 8.8.8.8; /0 permanece compatível."},"misconceptions":{"route":"ignores_routing_table"},"wrong_feedback":"Teste as rotas específicas antes de usar a linha que representa qualquer destino IPv4.","correct_feedback":"Correto. Sem rota mais específica, 0.0.0.0/0 é selecionada.","hints":[]},
    {"id":"5","number":5,"category":"Inferir","difficulty_level":4,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["IPv4","Subnet"],"title":"Mais de uma rota combina","scenario":"10.0.0.0/8 · 10.20.0.0/16 · 0.0.0.0/0 · Destino 10.20.30.40","instruction":"Qual prefixo vence?","fields":[field("route","Rota",["10.0.0.0/8","10.20.0.0/16","0.0.0.0/0"])],"correct_map":{"route":"10.20.0.0/16"},"feedback":{"route":"As três combinam; /16 é o prefixo compatível mais longo."},"misconceptions":{"route":"ignores_longest_prefix_match"},"wrong_feedback":"Compare a especificidade apenas entre as rotas que contêm o destino.","correct_feedback":"Correto. 10.20.0.0/16 é a rota compatível mais específica.","hints":[]},
    {"id":"6","number":6,"category":"Inferir","difficulty_level":4,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["IPv4","Subnet"],"title":"Prefixo maior só vale se combinar","scenario":"10.0.0.0/8 · 192.168.50.0/24 · 0.0.0.0/0 · Destino 10.20.30.40","instruction":"Qual prefixo vence?","fields":[field("route","Rota",["10.0.0.0/8","192.168.50.0/24","0.0.0.0/0"])],"correct_map":{"route":"10.0.0.0/8"},"feedback":{"route":"192.168.50.0/24 não contém 10.20.30.40."},"misconceptions":{"route":"chooses_largest_prefix_without_matching_destination"},"wrong_feedback":"O tamanho do prefixo só é comparado depois que a rota corresponde ao Destination IP.","correct_feedback":"Correto. A /24 não combina; entre as compatíveis, 10.0.0.0/8 vence /0.","hints":[]},
    {"id":"7","number":7,"category":"Integrar","difficulty_level":4,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["ARP","MAC","Frame"],"title":"Entrega após uma rota DIRECT","scenario":"R1: 192.168.10.1/24 · Destino 192.168.10.80 · Rota 192.168.10.0/24 DIRECT LAN","instruction":"Quem deve ser alcançado pela entrega L2?","fields":[field("l2","Destinatário",["O HOST 192.168.10.80","OUTRO ROTEADOR"])],"correct_map":{"l2":"o host 192.168.10.80"},"feedback":{"l2":"DIRECT indica que nenhum roteador intermediário é necessário."},"misconceptions":{"l2":"ignores_directly_connected_route"},"wrong_feedback":"Depois de selecionar DIRECT, observe quem está na própria rede conectada.","correct_feedback":"Correto. R1 pode resolver por ARP o host 192.168.10.80 e criar o novo frame.","hints":[]},
    {"id":"8","number":8,"category":"Sintetizar","difficulty_level":5,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["Next Hop","MAC","Frame"],"title":"Montar a entrega ao next hop","scenario":"Rota 192.168.20.0/24 via 10.0.0.2 WAN1 · Pacote para 192.168.20.50 · MAC de R2: RR","instruction":"Preencha os destinos depois da seleção da rota.","fields":[field("ip","IP Destination"),field("mac","Ethernet Destination")],"correct_map":{"ip":"192.168.20.50","mac":"rr"},"feedback":{"ip":"A rota não altera o destino IP final.","mac":"O novo frame é entregue ao MAC do next hop."},"misconceptions":{"ip":"assumes_route_changes_final_destination_ip","mac":"confuses_next_hop_with_final_destination"},"wrong_feedback":"Separe o destino final do pacote e o destinatário do novo enlace.","correct_feedback":"Correto. O IP final permanece 192.168.20.50 e o frame segue ao MAC RR.","hints":HINTS,"packet":{"destination_ip":"192.168.20.50","destination_mac":"RR","next_hop":"10.0.0.2"}},
    {"id":"9","number":9,"category":"Diagnosticar","difficulty_level":5,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["IPv4","Gateway"],"title":"Questionar uma saída inconsistente","scenario":"10.50.10.20 foi enviado ao gateway da Internet. Tabela: 10.0.0.0/8 via R2; 0.0.0.0/0 via Internet.","instruction":"Qual conclusão é sustentada?","fields":[field("conclusion","Conclusão",["O COMPORTAMENTO É INCONSISTENTE","A DEFAULT TEM PRIORIDADE"])],"correct_map":{"conclusion":"o comportamento é inconsistente"},"feedback":{"conclusion":"10.0.0.0/8 contém 10.50.10.20 e é mais específica que /0."},"misconceptions":{"conclusion":"assumes_default_route_has_priority"},"wrong_feedback":"Não aceite a saída sem testar o Destination IP contra cada prefixo.","correct_feedback":"Correto. A rota /8 via R2 deveria combinar e vencer a default.","hints":HINTS,"evidence":["Destino 10.50.10.20","Rota 10.0.0.0/8 via R2","Saída observada: Internet"]},
    {"id":"10","number":10,"category":"Diagnosticar / Sintetizar","difficulty_level":5,"primary":"ROUTING TABLE / ROUTE SELECTION","related":["IPv4","Subnet","Gateway","Next Hop","ARP","MAC","Frame"],"title":"Selecionar quatro caminhos","scenario":"172.16.0.0/12 → R2 · 172.16.20.0/24 → R3 · 172.16.20.128/25 → R4 · 0.0.0.0/0 → Internet","instruction":"Associe cada destino ao caminho selecionado.","fields":[field("a","172.16.20.50",["R2","R3","R4","INTERNET"]),field("b","172.16.20.180",["R2","R3","R4","INTERNET"]),field("c","172.16.80.20",["R2","R3","R4","INTERNET"]),field("d","8.8.8.8",["R2","R3","R4","INTERNET"])],"correct_map":{"a":"r3","b":"r4","c":"r2","d":"internet"},"feedback":{"a":"/24 vence /12.","b":"/25 vence /24 e /12.","c":"Somente /12 e /0 combinam; /12 vence.","d":"Somente /0 combina."},"misconceptions":{"a":"ignores_longest_prefix_match","b":"ignores_longest_prefix_match","c":"chooses_largest_prefix_without_matching_destination","d":"assumes_every_remote_destination_uses_default_gateway"},"wrong_feedback":"Para cada destino: marque matches, depois escolha o prefixo compatível mais longo.","correct_feedback":"Correto. A→R3, B→R4, C→R2 e D→Internet.","hints":HINTS},
]

ACTIVITY_MAP = {item["id"]: item for item in ACTIVITIES}
CAPABILITIES = ["Ler Destination Prefix, Next Hop e Interface","Distinguir DIRECT de via next hop","Aplicar longest prefix match","Usar a default somente sem escolha melhor","Integrar seleção L3 à entrega L2"]
MISCONCEPTION_LABELS = {
"assumes_every_remote_destination_uses_default_gateway":"Usa a default para todo destino remoto","ignores_routing_table":"Ignora a tabela de rotas","assumes_default_route_has_priority":"Dá prioridade à rota padrão","chooses_largest_prefix_without_matching_destination":"Compara prefixos antes de testar correspondência","confuses_destination_prefix_with_next_hop":"Confunde prefixo de destino com next hop","confuses_next_hop_with_final_destination":"Confunde next hop com destino final","assumes_every_route_requires_next_hop":"Supõe que toda rota exige next hop","ignores_directly_connected_route":"Ignora rotas diretamente conectadas","confuses_mac_table_with_routing_table":"Confunde tabela MAC com tabela de rotas","assumes_router_routes_using_destination_mac":"Supõe que o roteador escolhe rota pelo MAC","assumes_switch_uses_routing_table":"Supõe que switch L2 usa tabela de rotas","assumes_route_changes_final_destination_ip":"Supõe que a rota altera o destino IP","ignores_longest_prefix_match":"Ignora a rota compatível mais específica"}
