"""Checkpoint Switch V2: investigação controlada sobre estados e evidências."""


def token(key, text):
    return {"id": key, "text": text}


def slot(key, label, many=False):
    value = {"id": key, "label": label}
    if many:
        value["capacity"] = "many"
    return value


COMMON = {"primary": "SWITCH", "related": ["MAC", "FRAME"]}


ACTIVITIES = [
    {
        **COMMON, "id": "1", "number": 1, "category": "Aplicar", "difficulty_level": 3,
        "type": "switch_learning_interaction", "title": "Aprenda o Source", "scenario_key": "switch-a1", "mode": "exercise",
        "symptom": "A tabela está vazia. Um frame com Source CC e Destination AA entra por Gi0/3.",
        "instruction": "Inspecione o frame, identifique o campo usado para aprender e execute a associação.",
        "tools": ["board"], "required_actions": ["field:source", "port:3", "frame:run"], "required_evidence": [],
        "slots": [slot("field", "CAMPO OBSERVADO"), slot("port", "PORTA DE ENTRADA"), slot("association", "ASSOCIAÇÃO RESULTANTE")],
        "tokens": [token("source", "Source MAC: CC"), token("destination", "Destination MAC: AA"), token("g03", "Gi0/3"), token("g01", "Gi0/1"), token("cc3", "CC → Gi0/3")],
        "correct_map": {"source": "field", "g03": "port", "cc3": "association"},
        "feedback": {"destination": "Destination MAC orienta a decisão de saída; a aprendizagem usa Source MAC.", "g01": "O frame foi recebido em Gi0/3, não em Gi0/1."},
        "misconceptions": {"destination": "assumes_destination_mac_is_learned", "g01": "ignores_ingress_port"},
        "wrong_feedback": "Relacione Source CC à porta em que esse frame foi observado.",
        "hints": ["Separe o campo usado para aprender do campo usado para encaminhar.", "Observe o Source MAC e a porta marcada como ingresso."],
        "correct_feedback": "Correto. Gi0/3 recebeu o frame (RX +1), Source CC foi observado e CC → Gi0/3 foi adicionado à tabela.",
    },
    {
        **COMMON, "id": "2", "number": 2, "category": "Aplicar", "difficulty_level": 3,
        "type": "switch_forwarding_interaction", "title": "Encaminhe para o destino", "scenario_key": "switch-a2", "mode": "exercise",
        "symptom": "O frame entra em Gi0/1 e seu Destination MAC é CC. A tabela possui AA → Gi0/1, BB → Gi0/4 e CC → Gi0/7.",
        "instruction": "Inspecione Destination, selecione CC na tabela, marque a porta física e execute.",
        "tools": ["board"], "required_actions": ["field:destination", "mac:CC:CC:CC:CC:CC:CC", "port:7", "frame:run"], "required_evidence": [],
        "slots": [slot("field", "CAMPO CONSULTADO"), slot("entry", "ENTRADA ENCONTRADA"), slot("egress", "PORTA DE SAÍDA")],
        "tokens": [token("destination", "Destination MAC: CC"), token("source", "Source MAC: AA"), token("cc7", "CC → Gi0/7"), token("bb4", "BB → Gi0/4"), token("g07", "Gi0/7"), token("g04", "Gi0/4")],
        "correct_map": {"destination": "field", "cc7": "entry", "g07": "egress"},
        "feedback": {"source": "Source é usado para aprendizagem. A porta de saída é escolhida consultando Destination.", "bb4": "O destino deste frame é CC, não BB.", "g04": "A entrada de CC aponta Gi0/7."},
        "misconceptions": {"source": "assumes_destination_mac_is_learned", "g04": "assumes_switch_always_forwards"},
        "wrong_feedback": "Siga Destination CC até sua entrada na tabela e então até a porta física.",
        "hints": ["Comece pelo campo que representa quem deve receber o frame.", "Selecione a entrada CC e acompanhe a porta indicada."],
        "correct_feedback": "Correto. Destination CC encontra CC → Gi0/7; o switch encaminha por Gi0/7 e o TX aumenta em 1.",
    },
    {
        **COMMON, "id": "3", "number": 3, "category": "Inferir", "difficulty_level": 4,
        "type": "learn_and_forward_investigation", "title": "Aprenda e encaminhe", "scenario_key": "switch-a3", "mode": "exercise",
        "symptom": "Um frame Source DD, Destination BB entra por Gi0/2. A tabela já contém BB → Gi0/4.",
        "instruction": "Tome duas decisões diretamente no equipamento: aprendizagem e encaminhamento.",
        "tools": ["board"], "required_actions": ["field:source", "field:destination", "port:2", "port:4", "frame:run"], "required_evidence": [],
        "slots": [slot("learning", "APRENDIZADO"), slot("forwarding", "ENCAMINHAMENTO")],
        "tokens": [token("dd2", "DD → Gi0/2"), token("bb2", "BB → Gi0/2"), token("g04", "Saída Gi0/4"), token("g02", "Saída Gi0/2")],
        "correct_map": {"dd2": "learning", "g04": "forwarding"},
        "feedback": {"bb2": "BB está no Destination. A origem observada em Gi0/2 é DD.", "g02": "Gi0/2 é a entrada; a tabela aponta BB para Gi0/4."},
        "misconceptions": {"bb2": "assumes_destination_mac_is_learned", "g02": "ignores_ingress_port"},
        "wrong_feedback": "Faça duas leituras separadas: Source para aprender e Destination para encaminhar.",
        "hints": ["Procure duas operações diferentes no mesmo frame.", "Source DD entra em Gi0/2; Destination BB já aparece na tabela."],
        "correct_feedback": "Correto. O switch aprende DD → Gi0/2 e encaminha BB pela porta Gi0/4.",
    },
    {
        **COMMON, "id": "4", "number": 4, "category": "Inferir", "difficulty_level": 4,
        "type": "unknown_destination_investigation", "title": "Destino desconhecido", "scenario_key": "switch-a4", "mode": "exercise",
        "symptom": "EE não aparece na tabela. O frame entra em Gi0/1; Gi0/1, Gi0/2, Gi0/4 e Gi0/6 estão conectadas.",
        "instruction": "Consulte a tabela e selecione no switch todas as portas que devem transmitir.",
        "tools": ["board"], "required_actions": ["port:2", "port:4", "port:6", "frame:run"], "required_evidence": [],
        "slots": [slot("flood", "PORTAS QUE TRANSMITEM", True)],
        "tokens": [token("g01", "Gi0/1"), token("g02", "Gi0/2"), token("g04", "Gi0/4"), token("g06", "Gi0/6")],
        "correct_map": {"g02": "flood", "g04": "flood", "g06": "flood"},
        "feedback": {"g01": "Gi0/1 é a porta de entrada e não recebe uma cópia de volta."},
        "misconceptions": {"g01": "ignores_ingress_port"},
        "wrong_feedback": "O unknown unicast segue pelas outras portas conectadas elegíveis, excluindo o ingresso.",
        "hints": ["A ausência de EE na tabela muda o tipo de decisão.", "Considere todas as portas conectadas, menos Gi0/1."],
        "correct_feedback": "Correto. Gi0/2, Gi0/4 e Gi0/6 recebem cópias e cada contador TX aumenta em 1.",
    },
    {
        "primary": "SWITCH", "related": ["MAC"], "id": "5", "number": 5, "category": "Inferir", "difficulty_level": 4,
        "type": "mac_move_investigation", "title": "Host mudou de porta", "scenario_key": "switch-a5", "mode": "exercise",
        "symptom": "A tabela mostra AA → Gi0/1. PC-A será fisicamente conectado a Gi0/6.",
        "instruction": "Compare antes e depois, mova PC-A e gere um novo frame de origem AA.",
        "tools": ["board"], "actions": ["move-a", "generate-a"], "required_actions": ["action:move-a", "action:generate-a", "mac:AA:AA:AA:AA:AA:AA"], "required_evidence": ["source-aa-g6"],
        "evidence": [{"id": "source-aa-g6", "text": "Frame Source AA foi observado entrando por Gi0/6"}],
        "slots": [slot("update", "ALTERAÇÃO PREVISTA"), slot("evidence", "EVIDÊNCIA QUE PROVOCOU A ATUALIZAÇÃO")],
        "tokens": [token("aa6", "AA → Gi0/6"), token("aa1", "AA permanece em Gi0/1"), token("source6", "Source AA observado em Gi0/6"), token("destination6", "Destination AA observado em Gi0/6")],
        "correct_map": {"aa6": "update", "source6": "evidence"},
        "feedback": {"aa1": "Um novo frame de origem AA em Gi0/6 permite atualizar a localização.", "destination6": "O switch não atualiza a localização a partir do Destination MAC."},
        "misconceptions": {"aa1": "assumes_mac_table_is_current_truth", "destination6": "assumes_destination_mac_is_learned"},
        "wrong_feedback": "A mudança é sustentada pelo novo Source AA observado na nova porta.",
        "hints": ["Compare a associação antes e depois do novo tráfego.", "A evidência relevante está no Source MAC do frame que entra em Gi0/6."],
        "correct_feedback": "Correto. O switch observa Source AA em Gi0/6 e altera a entrada AA → Gi0/6, marcada como ALTERADO.",
    },
    {
        "primary": "SWITCH", "related": ["MAC"], "id": "6", "number": 6, "category": "Inferir", "difficulty_level": 4,
        "type": "cli_switch_investigation", "title": "CLI + switch", "scenario_key": "switch-a6", "mode": "investigation", "hide_mac_table": True,
        "symptom": "Descubra por qual porta o switch conhece o MAC bbbb.bbbb.bbbb de PC-B.",
        "instruction": "Escolha a ferramenta, selecione a linha encontrada e confirme na porta física.",
        "tools": ["switch_cli", "board"], "required_actions": ["command:show mac address-table", "mac:BB:BB:BB:BB:BB:BB", "port:5"], "required_evidence": ["mac-bb-g5"],
        "evidence": [{"id": "mac-bb-g5", "text": "MAC Table possui BB → Gi0/5"}],
        "slots": [slot("entry", "ENTRADA ENCONTRADA"), slot("port", "PORTA CONFIRMADA")],
        "tokens": [token("bb5", "bbbb.bbbb.bbbb → Gi0/5"), token("bb4", "bbbb.bbbb.bbbb → Gi0/4"), token("g05", "Gi0/5 · PC-B"), token("g07", "Gi0/7 · PC-C")],
        "correct_map": {"bb5": "entry", "g05": "port"},
        "feedback": {"bb4": "A linha produzida pela CLI aponta Gi0/5.", "g07": "Gi0/7 está associada a PC-C neste cenário."},
        "wrong_feedback": "Cruze a linha de BB na CLI com a porta física e o Port Inspector.",
        "hints": ["Procure uma evidência da perspectiva do switch.", "A tabela MAC pode ser consultada pelo comando show mac address-table."],
        "correct_feedback": "Correto. A CLI, a tabela visual e o Port Inspector convergem em BB → Gi0/5, conectado a PC-B.",
    },
    {
        **COMMON, "id": "7", "number": 7, "category": "Diagnosticar", "difficulty_level": 5,
        "type": "forwarding_inconsistency_investigation", "title": "Encaminhamento incoerente", "scenario_key": "switch-a7", "mode": "investigation",
        "symptom": "Um frame Destination BB é mostrado saindo por Gi0/7. Investigue a inconsistência.",
        "instruction": "Inspecione o frame, consulte a tabela, marque a saída incoerente e colete a evidência.",
        "tools": ["board"], "required_actions": ["field:destination", "mac:BB:BB:BB:BB:BB:BB", "port:7"], "required_evidence": ["mac-bb-g4"],
        "evidence": [{"id": "mac-bb-g4", "text": "MAC Table apresenta BB → Gi0/4"}],
        "slots": [slot("inconsistent", "ELEMENTO INCOERENTE"), slot("evidence", "EVIDÊNCIA")],
        "tokens": [token("g07", "Tentativa de saída Gi0/7"), token("g04", "Porta Gi0/4"), token("bb4", "BB → Gi0/4"), token("dest-bb", "Destination BB")],
        "correct_map": {"g07": "inconsistent", "bb4": "evidence"},
        "feedback": {"g04": "Gi0/4 combina com a associação; a saída mostrada em Gi0/7 é o elemento incoerente.", "dest-bb": "Destination identifica a chave consultada, mas BB → Gi0/4 é a evidência que contradiz Gi0/7."},
        "wrong_feedback": "Compare a saída mostrada com a porta apontada pela tabela.",
        "hints": ["Procure evidências em duas partes diferentes da bancada.", "Compare Destination BB com a linha BB da MAC Table."],
        "correct_feedback": "Correto. A saída mostrada em Gi0/7 não combina com a evidência BB → Gi0/4.",
    },
    {
        **COMMON, "id": "8", "number": 8, "category": "Diagnosticar", "difficulty_level": 5,
        "type": "link_state_investigation", "title": "Tabela diz uma coisa, link diz outra", "scenario_key": "switch-a8", "mode": "investigation", "hide_mac_table": False,
        "symptom": "PC-A não consegue alcançar PC-B.",
        "instruction": "Investigue sem assumir uma causa. Colete tabela e estado atual da interface.",
        "tools": ["switch_cli", "board"], "required_actions": ["command:show interfaces status", "port:4"], "required_evidence": ["mac-bb-g4", "g4-down"],
        "evidence": [{"id": "mac-bb-g4", "text": "BB está associado a Gi0/4"}, {"id": "g4-down", "text": "Gi0/4 está sem link"}],
        "slots": [slot("observed", "OBSERVADO", True), slot("hypothesis", "HIPÓTESE"), slot("less", "MENOS PROVÁVEL"), slot("unknown", "AINDA NÃO POSSO AFIRMAR")],
        "tokens": [token("association", "BB está associado a Gi0/4"), token("down", "Gi0/4 está sem link"), token("stale", "A associação pode estar desatualizada ou a topologia mudou"), token("no-info", "Ausência completa de informação anterior sobre BB"), token("off", "PC-B está desligado")],
        "correct_map": {"association": "observed", "down": "observed", "stale": "hypothesis", "no-info": "less", "off": "unknown"},
        "feedback": {"off": "Link down não prova que PC-B esteja desligado. Cabo, porta, desconexão ou mudança física continuam possíveis."},
        "misconceptions": {"off": "assumes_link_down_proves_host_offline"},
        "wrong_feedback": "Separe fatos observados, hipótese compatível, alternativa menos provável e causa ainda não demonstrada.",
        "hints": ["Pense em quais evidências podem ser coletadas no switch.", "Compare o que a MAC Table aprendeu anteriormente com o estado atual em show interfaces status."],
        "correct_feedback": "Correto. A entrada e o link down são observações. Elas sustentam investigação da interface, mas não provam que PC-B esteja desligado.",
    },
    {
        "primary": "SWITCH", "related": ["ARP", "MAC", "FRAME"], "id": "9", "number": 9, "category": "Diagnosticar", "difficulty_level": 5,
        "type": "end_to_end_investigation", "title": "Diagnóstico ponta a ponta", "scenario_key": "switch-a9", "mode": "investigation", "hide_mac_table": True,
        "symptom": "PC-A não consegue se comunicar com PC-B. Investigue.",
        "instruction": "Escolha suas ferramentas, colete evidências e construa uma conclusão limitada ao que elas sustentam.",
        "tools": ["host_terminal", "switch_cli", "board"], "required_actions": ["command:arp -a", "command:show mac address-table", "command:show interfaces status"], "required_evidence": ["arp-bb", "mac-bb-g4", "g4-down"],
        "evidence": [{"id": "arp-bb", "text": "ARP possui 192.168.10.20 → BB"}, {"id": "mac-bb-g4", "text": "MAC Table possui BB → Gi0/4"}, {"id": "g4-down", "text": "Gi0/4 está sem link"}],
        "slots": [slot("observed", "EVIDÊNCIA COLETADA", True), slot("less", "MENOS PROVÁVEL"), slot("strong", "EVIDÊNCIA FORTE"), slot("unknown", "NÃO POSSO AFIRMAR")],
        "tokens": [token("arp", "ARP possui .20 → BB"), token("mac", "MAC Table possui BB → Gi0/4"), token("down", "Gi0/4 está sem link"), token("arp-less", "Problema básico de resolução ARP"), token("path", "Há problema atual relacionado à interface/caminho de PC-B"), token("off", "PC-B está desligado")],
        "correct_map": {"arp": "observed", "mac": "observed", "down": "observed", "arp-less": "less", "path": "strong", "off": "unknown"},
        "feedback": {"off": "Nenhuma evidência demonstra que PC-B esteja desligado; apenas que a interface/caminho atual está sem link.", "arp-less": "A associação ARP já existe, tornando uma falha básica de resolução ARP menos provável."},
        "misconceptions": {"off": "jumps_from_evidence_to_unproven_cause", "arp-less": "confuses_arp_cache_with_mac_table"},
        "wrong_feedback": "Use cada fonte para o que ela demonstra: host, ARP, switch, tabela e estado da interface.",
        "hints": ["Pense em quais evidências podem ser coletadas no host e no switch.", "Talvez valha comparar o que o host conhece com o que o switch conhece e com o estado da porta."],
        "correct_feedback": "Correto. ARP e MAC Table existem, Gi0/4 está down e isso sustenta um problema atual no caminho da interface, sem provar que PC-B esteja desligado.",
    },
    {
        "primary": "SWITCH", "related": ["ARP", "MAC", "FRAME"], "id": "10", "number": 10, "category": "Diagnosticar / Sintetizar", "difficulty_level": 5,
        "type": "switch_troubleshooting_challenge", "title": "Switch Troubleshooting Challenge", "scenario_key": "switch-a10", "mode": "investigation", "hide_mac_table": True,
        "symptom": "Depois de uma alteração física no ambiente, PC-A deixou de alcançar PC-B.",
        "instruction": "Investigue, formule uma hipótese e teste-a gerando tráfego controlado de PC-B.",
        "tools": ["host_terminal", "switch_cli", "board"], "actions": ["generate-b", "send-a-b"],
        "required_actions": ["command:arp -a", "command:show mac address-table", "command:show interfaces status", "action:generate-b", "action:send-a-b"],
        "required_evidence": ["initial-bb-g4", "g4-down", "source-bb-g6", "updated-bb-g6"],
        "evidence": [{"id": "initial-bb-g4", "text": "Inicialmente BB estava associado a Gi0/4"}, {"id": "g4-down", "text": "Gi0/4 estava sem link"}, {"id": "source-bb-g6", "text": "Frame Source BB chegou por Gi0/6"}, {"id": "updated-bb-g6", "text": "MAC Table atualizou BB → Gi0/6"}],
        "slots": [slot("initial", "EVIDÊNCIA INICIAL"), slot("physical", "EVIDÊNCIA FÍSICA"), slot("new", "NOVA EVIDÊNCIA"), slot("change", "ALTERAÇÃO OBSERVADA"), slot("conclusion", "CONCLUSÃO")],
        "tokens": [token("bb4", "BB estava associado a Gi0/4"), token("g4down", "Gi0/4 estava sem link"), token("source6", "Frame Source BB chegou por Gi0/6"), token("bb6", "MAC Table atualizou BB → Gi0/6"), token("relearn", "O switch reaprendeu BB pela origem observada na nova porta"), token("off", "PC-B estava definitivamente desligado"), token("clear", "Foi necessário limpar manualmente a tabela")],
        "correct_map": {"bb4": "initial", "g4down": "physical", "source6": "new", "bb6": "change", "relearn": "conclusion"},
        "feedback": {"off": "As evidências nunca demonstraram que PC-B estivesse desligado.", "clear": "Nenhuma limpeza é necessária: o novo Source BB permite aprendizado dinâmico em Gi0/6."},
        "misconceptions": {"off": "jumps_from_evidence_to_unproven_cause", "clear": "assumes_mac_table_is_current_truth"},
        "wrong_feedback": "Reconstrua a investigação em ordem: estado inicial, estado físico, novo frame, mudança na tabela e conclusão sustentada.",
        "hints": ["Compare a associação antiga com o estado atual das interfaces.", "Gere tráfego de PC-B e observe qual campo do novo frame permite atualizar a tabela."],
        "correct_feedback": "Correto. O novo Source BB em Gi0/6 faz o switch reaprender BB → Gi0/6; o próximo A → B sai por Gi0/6 e TX aumenta em 1.",
    },
]

ACTIVITY_MAP = {activity["id"]: activity for activity in ACTIVITIES}
CAPABILITIES = ["Inspecionar equipamento", "Cruzar host e switch", "Coletar evidências", "Comparar estados", "Testar hipóteses", "Separar observação e causa", "Interpretar contadores", "Acompanhar aprendizado MAC", "Diagnosticar interface", "Concluir sem extrapolar"]
MISCONCEPTION_LABELS = {
    "assumes_mac_table_is_current_truth": "Tabela MAC como verdade atual absoluta",
    "assumes_link_down_proves_host_offline": "Link down prova host desligado",
    "confuses_arp_cache_with_mac_table": "Cache ARP × tabela MAC",
    "assumes_destination_mac_is_learned": "Aprendizado pelo Destination MAC",
    "ignores_ingress_port": "Ignora a porta de entrada",
    "assumes_switch_always_forwards": "Switch sempre encaminha",
    "assumes_unknown_destination_is_dropped": "Unknown unicast descartado",
    "assumes_cli_entry_guarantees_current_connectivity": "Entrada CLI garante conectividade atual",
    "jumps_from_evidence_to_unproven_cause": "Evidência transformada em causa não provada",
    "uses_irrelevant_layer_evidence_as_proof": "Evidência de camada irrelevante como prova",
}
