"""Structured checkpoint for the TCP x UDP concept module."""


def field(name, label, options=None):
    return {"name": name, "label": label, "options": options or []}


HINTS = [
    "Compare as propriedades oferecidas pelo transporte, não rótulos como rápido ou lento.",
    "Separe o comportamento do próprio TCP ou UDP do que uma aplicação pode implementar acima deles.",
]


ACTIVITIES = [
    {
        "id": "1", "number": 1, "category": "Classificar", "difficulty_level": 3,
        "primary": "TCP / UDP", "related": ["Application"],
        "title": "Datagramas sem retransmissão automática",
        "scenario": "A aplicação envia datagramas independentes. O transporte não realiza retransmissão automática.",
        "instruction": "Classifique o modelo de transporte.",
        "fields": [field("protocol", "Protocolo", ["TCP", "UDP"])],
        "correct_map": {"protocol": "udp"},
        "feedback": {"protocol": "UDP transporta datagramas independentes sem retransmissão automática embutida."},
        "misconceptions": {"protocol": "confuses_datagram_with_tcp_stream"},
        "wrong_feedback": "Observe se os dados são um fluxo ou datagramas independentes.",
        "correct_feedback": "Correto. Esse é o modelo de datagramas oferecido pelo UDP.", "hints": [],
    },
    {
        "id": "2", "number": 2, "category": "Classificar", "difficulty_level": 3,
        "primary": "TCP / UDP", "related": ["Application"],
        "title": "Fluxo ordenado",
        "scenario": "O transporte deve fornecer à aplicação um fluxo ordenado e recuperar perdas quando possível.",
        "instruction": "Classifique o modelo de transporte.",
        "fields": [field("protocol", "Protocolo", ["TCP", "UDP"])],
        "correct_map": {"protocol": "tcp"},
        "feedback": {"protocol": "TCP oferece diretamente fluxo ordenado e mecanismos de recuperação."},
        "misconceptions": {"protocol": "assumes_udp_provides_ordering"},
        "wrong_feedback": "Pergunte qual protocolo já fornece ordem e recuperação no transporte.",
        "correct_feedback": "Correto. Entre TCP e UDP, TCP fornece essas propriedades diretamente.", "hints": [],
    },
    {
        "id": "3", "number": 3, "category": "Aplicar", "difficulty_level": 4,
        "primary": "TCP / UDP", "related": ["IPv4"],
        "title": "Perda de um datagrama UDP", "scenario": "UDP envia 1, 2, 3 e 4. O datagrama 3 é perdido.",
        "instruction": "O que o próprio UDP faz automaticamente?",
        "fields": [field("action", "Ação", ["NÃO RETRANSMITE O 3", "RETRANSMITE O 3", "ENCERRA UMA CONEXÃO"])],
        "correct_map": {"action": "não retransmite o 3"},
        "feedback": {"action": "UDP não integra confirmação ou retransmissão automática; também não encerra uma conexão TCP-like."},
        "misconceptions": {"action": "assumes_udp_retransmits_automatically"},
        "wrong_feedback": "Qual protocolo estudado possui confirmação e retransmissão integradas ao transporte?",
        "correct_feedback": "Correto. O destino observa 1, 2 e 4; UDP não retransmite 3 automaticamente.", "hints": HINTS,
    },
    {
        "id": "4", "number": 4, "category": "Ordenar", "difficulty_level": 4,
        "primary": "TCP / UDP", "related": ["Application"],
        "title": "Recuperação conceitual no TCP", "scenario": "TCP transporta A B C D. C é perdido.",
        "instruction": "Ordene os próximos acontecimentos conceituais.",
        "fields": [
            field("first", "1º", ["DETECTAR AUSÊNCIA", "RECUPERAR / RETRANSMITIR", "ENTREGAR FLUXO COMPLETO EM ORDEM"]),
            field("second", "2º", ["DETECTAR AUSÊNCIA", "RECUPERAR / RETRANSMITIR", "ENTREGAR FLUXO COMPLETO EM ORDEM"]),
            field("third", "3º", ["DETECTAR AUSÊNCIA", "RECUPERAR / RETRANSMITIR", "ENTREGAR FLUXO COMPLETO EM ORDEM"]),
        ],
        "correct_map": {"first": "detectar ausência", "second": "recuperar / retransmitir", "third": "entregar fluxo completo em ordem"},
        "feedback": {"first": "Primeiro a ausência precisa ser percebida conceitualmente.", "second": "Depois ocorre a recuperação.", "third": "Só então o fluxo completo pode ser entregue em ordem."},
        "misconceptions": {"second": "assumes_tcp_guarantees_delivery_under_any_failure"},
        "wrong_feedback": "A recuperação ocorre entre perceber a ausência e entregar o fluxo completo.",
        "correct_feedback": "Correto. TCP detecta a ausência, recupera a parte e entrega o fluxo completo em ordem.", "hints": HINTS,
    },
    {
        "id": "5", "number": 5, "category": "Comparar", "difficulty_level": 4,
        "primary": "TCP / UDP", "related": ["IPv4"],
        "title": "Chegada fora de ordem", "scenario": "A rede entrega 1, 3 e 2.",
        "instruction": "Associe cada protocolo ao comportamento fornecido.",
        "fields": [field("tcp", "TCP", ["FORNECE FLUXO ORDENADO", "NÃO OFERECE REORDENAÇÃO GARANTIDA"]), field("udp", "UDP", ["FORNECE FLUXO ORDENADO", "NÃO OFERECE REORDENAÇÃO GARANTIDA"])],
        "correct_map": {"tcp": "fornece fluxo ordenado", "udp": "não oferece reordenação garantida"},
        "feedback": {"tcp": "TCP disponibiliza o fluxo na ordem apropriada.", "udp": "UDP não reordena datagramas para a aplicação por conta própria."},
        "misconceptions": {"udp": "assumes_udp_provides_ordering"},
        "wrong_feedback": "Diferencie ordem no fluxo TCP de datagramas UDP recebidos independentemente.",
        "correct_feedback": "Correto. TCP fornece o fluxo ordenado; UDP não garante ordenação dos datagramas.", "hints": HINTS,
    },
    {
        "id": "6", "number": 6, "category": "Diferenciar", "difficulty_level": 4,
        "primary": "TCP / UDP", "related": ["Application"],
        "title": "HELLO e WORLD", "scenario": "A aplicação envia “HELLO” e depois “WORLD”.",
        "instruction": "Associe preservação de envios e fluxo de bytes.",
        "fields": [field("boundaries", "Preserva os dois como datagramas", ["TCP", "UDP"]), field("stream", "Oferece um fluxo de bytes", ["TCP", "UDP"])],
        "correct_map": {"boundaries": "udp", "stream": "tcp"},
        "feedback": {"boundaries": "UDP preserva os limites dos datagramas.", "stream": "TCP oferece HELLOWORLD como fluxo, sem preservar cada envio como mensagem."},
        "misconceptions": {"boundaries": "assumes_tcp_preserves_message_boundaries", "stream": "confuses_datagram_with_tcp_stream"},
        "wrong_feedback": "TCP fornece um fluxo de bytes. Não trate cada operação de envio como mensagem preservada.",
        "correct_feedback": "Correto. UDP preserva os dois datagramas; TCP fornece um fluxo de bytes.", "hints": HINTS,
    },
    {
        "id": "7", "number": 7, "category": "Avaliar", "difficulty_level": 4,
        "primary": "TCP / UDP", "related": ["Application"],
        "title": "Baixa latência decide tudo?", "scenario": "O técnico afirma: “A aplicação precisa ter baixa latência, então obrigatoriamente devemos escolher UDP.”",
        "instruction": "Avalie a conclusão.",
        "fields": [field("verdict", "Conclusão", ["NÃO JUSTIFICADA", "JUSTIFICADA"])],
        "correct_map": {"verdict": "não justificada"},
        "feedback": {"verdict": "Latência isolada não descreve todas as propriedades exigidas nem o protocolo superior."},
        "misconceptions": {"verdict": "assumes_udp_is_always_faster"},
        "wrong_feedback": "Menos mecanismos embutidos não permite concluir sozinho qual aplicação terá melhor desempenho.",
        "correct_feedback": "Correto. Precisamos conhecer os requisitos completos e como o protocolo superior funciona.", "hints": HINTS,
    },
    {
        "id": "8", "number": 8, "category": "Refutar", "difficulty_level": 5,
        "primary": "TCP / UDP", "related": ["Application"],
        "title": "UDP necessariamente perde?", "scenario": "100 datagramas UDP foram enviados e 100 recebidos. Um técnico diz que isso é impossível porque UDP perde dados.",
        "instruction": "Escolha a refutação correta.",
        "fields": [field("refutation", "Refutação", ["UDP NÃO GARANTE ENTREGA, MAS A PERDA NÃO É OBRIGATÓRIA", "TODO DATAGRAMA UDP PRECISA SER PERDIDO"])],
        "correct_map": {"refutation": "udp não garante entrega, mas a perda não é obrigatória"},
        "feedback": {"refutation": "Ausência de garantia não significa ocorrência necessária de perda."},
        "misconceptions": {"refutation": "assumes_udp_always_loses_packets"},
        "wrong_feedback": "Diferencie não garantir um resultado de tornar o resultado impossível.",
        "correct_feedback": "Correto. UDP pode entregar todos os datagramas; ele apenas não fornece garantia de entrega.", "hints": HINTS,
    },
    {
        "id": "9", "number": 9, "category": "Raciocinar", "difficulty_level": 5,
        "primary": "TCP / UDP", "related": ["Application"],
        "title": "Controle acima do UDP", "scenario": "O protocolo X usa UDP e implementa IDs, confirmações e retransmissão próprios.",
        "instruction": "Isso contradiz a ausência de entrega confiável embutida no UDP?",
        "fields": [field("contradiction", "Contradição?", ["NÃO", "SIM"])],
        "correct_map": {"contradiction": "não"},
        "feedback": {"contradiction": "Os mecanismos pertencem ao protocolo superior, não ao próprio UDP."},
        "misconceptions": {"contradiction": "assumes_udp_cannot_be_reliable_at_application_layer"},
        "wrong_feedback": "Separe as propriedades do UDP das propriedades implementadas acima dele.",
        "correct_feedback": "Correto. UDP não fornece esses mecanismos por si, mas não impede que outro nível os implemente.", "hints": HINTS,
    },
    {
        "id": "10", "number": 10, "category": "Sintetizar", "difficulty_level": 5,
        "primary": "TCP / UDP", "related": ["IPv4", "Routing", "ICMP", "Application"],
        "title": "Escolha pelo serviço necessário", "scenario": "Três aplicações possuem requisitos diferentes sobre fluxo, mensagens e recuperação.",
        "instruction": "Associe cada aplicação ao transporte que atende diretamente ao requisito descrito.",
        "fields": [
            field("a", "A · fluxo, ordem e recuperação no transporte", ["TCP", "UDP", "UDP PODE SERVIR COMO BASE"]),
            field("b", "B · mensagens, tolera perdas, sem recuperação automática", ["TCP", "UDP", "UDP PODE SERVIR COMO BASE"]),
            field("c", "C · datagramas e controle no protocolo superior", ["TCP", "UDP", "UDP PODE SERVIR COMO BASE"]),
        ],
        "correct_map": {"a": "tcp", "b": "udp", "c": "udp pode servir como base"},
        "feedback": {"a": "TCP oferece diretamente fluxo, ordem e recuperação.", "b": "UDP oferece datagramas sem recuperação automática.", "c": "UDP pode ser a base para controle implementado acima."},
        "misconceptions": {"a": "assumes_udp_is_better_for_realtime_without_requirements", "b": "assumes_tcp_is_better_for_every_application", "c": "assumes_udp_cannot_be_reliable_at_application_layer"},
        "wrong_feedback": "Não procure um vencedor universal; compare os requisitos de cada aplicação.",
        "correct_feedback": "Correto. A escolha depende do serviço de transporte necessário, não de bom × ruim.", "hints": HINTS,
    },
]


ACTIVITY_MAP = {item["id"]: item for item in ACTIVITIES}
CAPABILITIES = [
    "Distinguir fluxo de bytes e datagramas", "Interpretar perda e ordem em TCP e UDP",
    "Reconhecer conexão e retransmissão conceitualmente", "Separar transporte de routing",
    "Escolher o serviço pelo requisito da aplicação",
]
MISCONCEPTION_LABELS = {
    "assumes_tcp_guarantees_delivery_under_any_failure": "Trata TCP como garantia absoluta",
    "assumes_udp_always_loses_packets": "Supõe que UDP sempre perde dados",
    "assumes_udp_is_always_faster": "Supõe que UDP sempre é mais rápido",
    "assumes_tcp_is_always_slow": "Supõe que TCP sempre é lento",
    "assumes_udp_cannot_be_reliable_at_application_layer": "Ignora controles implementados acima do UDP",
    "assumes_tcp_preserves_message_boundaries": "Supõe que TCP preserva limites de mensagens",
    "assumes_udp_provides_ordering": "Supõe que UDP garante ordenação",
    "assumes_udp_retransmits_automatically": "Supõe retransmissão automática no UDP",
    "assumes_tcp_and_udp_choose_network_routes": "Supõe que TCP e UDP escolhem rotas",
    "confuses_transport_with_ip_routing": "Confunde transporte com roteamento IP",
    "confuses_datagram_with_tcp_stream": "Confunde datagrama com fluxo TCP",
    "assumes_connectionless_means_no_endpoints": "Interpreta connectionless como ausência de endpoints",
    "assumes_tcp_is_better_for_every_application": "Trata TCP como melhor para toda aplicação",
    "assumes_udp_is_better_for_realtime_without_requirements": "Escolhe UDP para tempo real sem analisar requisitos",
    "confuses_icmp_with_tcp_or_udp": "Confunde ICMP com TCP ou UDP",
}
